FROM hashicorp/terraform:1.9.5
LABEL LICENSE="MPL 2.0, custom terms"
LABEL LICENSE_URL="https://github.com/hashicorp/terraform/blob/main/LICENSE"

RUN apk add --no-cache bash

ENTRYPOINT ["/bin/bash","-c"]