apiVersion: v1
kind: Service
metadata:
  name: {{ include "polycentric.fullname" . }}
  labels:
    {{- include "polycentric.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "polycentric.selectorLabels" . | nindent 4 }}
