//! End-to-end moderator report pipeline test
//!
//! Note: the test was generated by Claude.
//!
//! A moderator listed in the moderation service's `moderator` table reports a
//! post as violent, and the service publishes a matching `violence` label. A
//! second report of the same post from an identity absent from that table is
//! expected to produce nothing.
//!
//! It is `#[ignore]`d by default, because it requires the server stack
//! running before the test can run.

use ed25519_dalek::{Signer, SigningKey};
use moderation_entity::moderator_model;
use polycentric_common::models::{
    collections,
    protos_v2::{
        Content, ContentDigest, ContentDigestType, Event, EventBundle, EventKey, Identity, KeyType,
        Labels, ListEventsFilters, ListEventsRequest, Post, PublicKey, PutEventsRequest, Report,
        ReportCategory, SerializedContent, SignedEvent, VectorClock, content::ContentBody,
        event_sync_service_client::EventSyncServiceClient,
    },
};
use polycentric_core::query::channel;
use prost::Message;
use sea_orm::{ActiveModelTrait, ActiveValue::Set, ConnectOptions, Database};
use sha2::{Digest, Sha256};
use std::{
    env::var,
    process::Stdio,
    sync::{
        Arc,
        atomic::{AtomicBool, Ordering},
    },
    time::{Duration, Instant, SystemTime, UNIX_EPOCH},
};
use time::OffsetDateTime;
use tokio::{
    io::{AsyncBufReadExt, BufReader},
    time::sleep,
};

const CREATED_AT: u64 = 1736942400000;
const HOUR: u64 = 3_600_000;

/// Grace period allowed for a label that should never be published.
const UNTRUSTED_REPORT_GRACE: Duration = Duration::from_secs(10);

fn server_endpoint() -> String {
    var("POLYCENTRIC_TEST_SERVER").unwrap_or("http://localhost:3000".to_string())
}
fn database_endpoint() -> String {
    var("POLYCENTRIC_TEST_DATABASE_URL")
        .unwrap_or("postgres://postgres:testing@localhost:5432".to_string())
}
fn os_endpoint() -> String {
    var("POLYCENTRIC_TEST_OS_ENDPOINT").unwrap_or("http://localhost:9000".to_string())
}
fn kafka_endpoint() -> String {
    var("POLYCENTRIC_TEST_KAFKA_BROKERS").unwrap_or("localhost:9092".to_string())
}

#[tokio::test]
#[ignore = "spawns the moderation service against a live stack"]
async fn moderator_report_publishes_label_and_untrusted_report_does_not() {
    let service_key = signing_key(0);
    let (service_identity, service_genesis) = make_identity(&service_key);
    put_events(vec![service_genesis])
        .await
        .expect("seed moderation identity (is the stack up?)");

    let ready = Arc::new(AtomicBool::new(false));
    let mut child =
        spawn_moderation_service(&hex::encode(service_key.to_bytes()), &service_identity);
    tee_stderr(&mut child, ready.clone());

    let deadline = Instant::now() + Duration::from_secs(45);
    while !ready.load(Ordering::SeqCst) && Instant::now() < deadline {
        sleep(Duration::from_millis(200)).await;
    }
    sleep(Duration::from_secs(5)).await;

    let moderator_key = signing_key(1);
    let (moderator_identity, moderator_genesis) = make_identity(&moderator_key);
    let outsider_key = signing_key(2);
    let (outsider_identity, outsider_genesis) = make_identity(&outsider_key);
    let author_key = signing_key(3);
    let (author_identity, author_genesis) = make_identity(&author_key);
    put_events(vec![moderator_genesis, outsider_genesis, author_genesis])
        .await
        .expect("put reporter and author identities");

    trust_moderator(&moderator_identity)
        .await
        .expect("insert moderator row");

    let (reported_post_key, reported_post) = make_post(&author_key, &author_identity, 1);
    let (ignored_post_key, ignored_post) = make_post(&author_key, &author_identity, 2);
    put_events(vec![reported_post, ignored_post])
        .await
        .expect("put reported posts");

    put_events(vec![make_report(
        &outsider_key,
        &outsider_identity,
        &ignored_post_key,
        ReportCategory::Violence,
    )])
    .await
    .expect("put untrusted report");

    put_events(vec![make_report(
        &moderator_key,
        &moderator_identity,
        &reported_post_key,
        ReportCategory::Violence,
    )])
    .await
    .expect("put moderator report");

    let mut labeled = false;
    let deadline = Instant::now() + Duration::from_secs(60);
    while !labeled && Instant::now() < deadline {
        labeled = label_exists(&service_identity, &reported_post_key, "violence")
            .await
            .unwrap_or(false);
        if !labeled {
            sleep(Duration::from_secs(1)).await;
        }
    }

    sleep(UNTRUSTED_REPORT_GRACE).await;
    let untrusted_labeled = label_exists(&service_identity, &ignored_post_key, "violence")
        .await
        .unwrap_or(false);

    let _ = child.start_kill();

    assert!(
        labeled,
        "no violence label was published for the moderator's report"
    );
    assert!(
        !untrusted_labeled,
        "a label was published for a report from an identity that is not a moderator"
    );
}

fn spawn_moderation_service(
    service_seed_hex: &str,
    service_identity: &str,
) -> tokio::process::Child {
    tokio::process::Command::new(env!("CARGO_BIN_EXE_moderation-service"))
        .env("DATABASE_URL", database_endpoint())
        .env("CONTENT_BLOB_OS_BUCKET", "polycentric-blobs")
        .env("CONTENT_BLOB_OS_ENDPOINT", os_endpoint())
        .env("CONTENT_BLOB_OS_FORCE_PATH_STYLE", "true")
        .env("CONTENT_BLOB_OS_ACCESS_KEY", "rustfsadmin")
        .env("CONTENT_BLOB_OS_SECRET_KEY", "rustfsadmin")
        .env("POLYCENTRIC_KAFKA_BROKERS", kafka_endpoint())
        .env("POLYCENTRIC_KAFKA_AUTO_OFFSET_RESET", "earliest")
        .env("POLYCENTRIC_MODERATION_SIGNING_KEY", service_seed_hex)
        .env("POLYCENTRIC_MODERATION_IDENTITY", service_identity)
        .env("POLYCENTRIC_MODERATION_SERVERS", server_endpoint())
        .env("RUST_LOG", "info")
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .kill_on_drop(true)
        .spawn()
        .expect("spawn moderation-service")
}

/// Echo the child's stderr to the test output and flip `ready` once it has
/// synced with the servers (after which its Kafka consumer is created).
fn tee_stderr(child: &mut tokio::process::Child, ready: Arc<AtomicBool>) {
    let stderr = child.stderr.take().expect("piped stderr");
    tokio::spawn(async move {
        let mut lines = BufReader::new(stderr).lines();
        while let Ok(Some(line)) = lines.next_line().await {
            if line.contains("sync:") {
                ready.store(true, Ordering::SeqCst);
            }
            eprintln!("[moderation] {line}");
        }
    });
}

/// Insert `identity` into the moderation schema's `moderator` table. The
/// service creates that table when it runs migrations at startup, so this
/// must follow its boot.
async fn trust_moderator(identity: &str) -> Result<(), String> {
    let mut options = ConnectOptions::new(database_endpoint());
    options.set_schema_search_path("moderation");
    let db = Database::connect(options)
        .await
        .map_err(|e| e.to_string())?;

    let now = OffsetDateTime::now_utc();
    moderator_model::ActiveModel {
        identity: Set(identity.to_string()),
        created_at: Set(now),
        updated_at: Set(now),
    }
    .insert(&db)
    .await
    .map_err(|e| e.to_string())?;

    Ok(())
}

async fn put_events(bundles: Vec<EventBundle>) -> Result<(), String> {
    let mut client = EventSyncServiceClient::new(channel(&server_endpoint()).await?);
    let errors = client
        .put_events(PutEventsRequest {
            event_bundles: bundles,
        })
        .await
        .map_err(|e| e.to_string())?
        .into_inner()
        .errors;
    if errors.is_empty() {
        Ok(())
    } else {
        Err(format!("server rejected events: {errors:?}"))
    }
}

/// Whether a labels event under `identity` applies `label` to `target`.
async fn label_exists(identity: &str, target: &EventKey, label: &str) -> Result<bool, String> {
    let bundles = EventSyncServiceClient::new(channel(&server_endpoint()).await?)
        .list_events(ListEventsRequest {
            filters: Some(ListEventsFilters {
                collection: Some(collections::LABELS),
                identity: Some(identity.to_string()),
                ..Default::default()
            }),
            size: Some(100),
        })
        .await
        .map_err(|e| e.to_string())?
        .into_inner()
        .event_bundles;

    Ok(bundles.iter().any(|b| {
        let Some(content) = b
            .serialized_content
            .as_ref()
            .and_then(|c| Content::decode(c.content_bytes.as_slice()).ok())
        else {
            return false;
        };
        matches!(
            content.content_body,
            Some(ContentBody::Labels(Labels { event_key: Some(ref k), ref label_values }))
                if event_keys_match(k, target) && label_values.iter().any(|v| v == label)
        )
    }))
}

fn event_keys_match(a: &EventKey, b: &EventKey) -> bool {
    a.collection == b.collection
        && a.identity == b.identity
        && a.sequence == b.sequence
        && a.signed_by.as_ref().map(|k| (&k.key_type, &k.key))
            == b.signed_by.as_ref().map(|k| (&k.key_type, &k.key))
}

/// A single-key genesis identity bundle and its derived identity string.
fn make_identity(key: &SigningKey) -> (String, EventBundle) {
    let content = Identity {
        rotation_keys: vec![public_key_of(key)],
        signing_keys: vec![],
        revocation_bounds: vec![],
        servers: None,
        recovery_key: None,
        recovery_signature: None,
    };
    let identity = content.derive_hex_key();
    let bundle = signed_bundle(
        &identity,
        key,
        collections::IDENTITY,
        Content {
            content_body: Some(ContentBody::Identity(content)),
        },
        CREATED_AT,
        1,
    );
    (identity, bundle)
}

/// A text-only feed post at `sequence`, plus its event key.
fn make_post(key: &SigningKey, identity: &str, sequence: u64) -> (EventKey, EventBundle) {
    let post = Post {
        text: format!("moderator report e2e post {sequence}"),
        reply: None,
        images: vec![],
        quote: None,
        links: vec![],
        labels: vec![],
        attributed_to: vec![],
    };
    let bundle = signed_bundle(
        identity,
        key,
        collections::FEED,
        Content {
            content_body: Some(ContentBody::Post(post)),
        },
        CREATED_AT + HOUR,
        sequence,
    );
    let event_key = EventKey {
        collection: collections::FEED,
        identity: identity.to_string(),
        signed_by: Some(public_key_of(key)),
        sequence,
    };
    (event_key, bundle)
}

/// A report of `target` under `category`, as the first event in the
/// reporter's report collection.
fn make_report(
    key: &SigningKey,
    identity: &str,
    target: &EventKey,
    category: ReportCategory,
) -> EventBundle {
    signed_bundle(
        identity,
        key,
        collections::REPORTS,
        Content {
            content_body: Some(ContentBody::Report(Report {
                event_key: Some(target.clone()),
                category: category as i32,
                additional_info: "moderator report e2e".to_string(),
            })),
        },
        CREATED_AT + HOUR,
        1,
    )
}

/// Build, sign, and bundle the event at `sequence` in `collection` for `key`.
fn signed_bundle(
    identity: &str,
    key: &SigningKey,
    collection: i32,
    content: Content,
    created_at: u64,
    sequence: u64,
) -> EventBundle {
    let content_bytes = content.encode_to_vec();
    let event = Event {
        key: Some(EventKey {
            collection,
            identity: identity.to_string(),
            signed_by: Some(public_key_of(key)),
            sequence,
        }),
        identity_sequence: 1,
        vector_clock: Some(VectorClock {
            sequence: vec![sequence],
        }),
        previous_signature: vec![],
        previous_root: vec![],
        content_digest: Some(sha256_digest(&content_bytes)),
        created_at,
        application: None,
    };
    let event_bytes = event.encode_to_vec();
    EventBundle {
        signed_event: Some(SignedEvent {
            signature: key.sign(&event_bytes).to_bytes().to_vec(),
            event_bytes,
        }),
        serialized_content: Some(SerializedContent { content_bytes }),
        event_proofs: vec![],
        meta: None,
    }
}

fn signing_key(salt: u8) -> SigningKey {
    SigningKey::from_bytes(&unique_bytes(salt))
}

/// 32 bytes that are distinct per run and per `salt`, derived from the wall
/// clock and pid. Used to keep identities unique across runs — these are test
/// fixtures, not secrets, so no CSPRNG is needed.
fn unique_bytes(salt: u8) -> [u8; 32] {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let mut seed = nanos.to_le_bytes().to_vec();
    seed.extend_from_slice(&std::process::id().to_le_bytes());
    seed.push(salt);
    Sha256::digest(seed).into()
}

fn public_key_of(key: &SigningKey) -> PublicKey {
    PublicKey {
        key_type: KeyType::Ed25519 as i32,
        key: key.verifying_key().to_bytes().to_vec(),
    }
}

fn sha256_digest(bytes: &[u8]) -> ContentDigest {
    ContentDigest {
        r#type: ContentDigestType::Sha256 as i32,
        value: Sha256::digest(bytes).to_vec(),
    }
}
