#!/usr/bin/env node
// Vendors the Twemoji SVGs: copies them to apps/harbor/public/twemoji/ for
// the web and packs them into src/common/emoji/twemoji/*.json for native.
//
//   curl -L -o twemoji.tar.gz https://github.com/jdecked/twemoji/archive/refs/tags/v17.0.3.tar.gz
//   mkdir twemoji && tar -xzf twemoji.tar.gz -C twemoji --strip-components=1 '*/assets/svg/*' '*/LICENSE*'
//   node tools/twemoji/generate.mjs twemoji

import {
  copyFileSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const app = join(root, 'apps', 'harbor');
const src = join(process.argv[2], 'assets', 'svg');
const web = join(app, 'public', 'twemoji');
const emojiDir = join(app, 'src', 'common', 'emoji');

rmSync(web, { recursive: true, force: true });
mkdirSync(web, { recursive: true });
const chunks = join(emojiDir, 'twemoji');
rmSync(chunks, { recursive: true, force: true });
mkdirSync(chunks, { recursive: true });

// Native loads the SVG markup from JSON; chunked by the first code point's
// leading hex digits so only the blocks a screen uses get parsed.
const chunkOf = (code) => code.split('-')[0].padStart(5, '0').slice(0, 4);
const byChunk = {};
let count = 0;
for (const file of readdirSync(src).sort()) {
  if (!file.endsWith('.svg')) continue;
  copyFileSync(join(src, file), join(web, file));
  const code = file.slice(0, -4);
  const chunk = chunkOf(code);
  byChunk[chunk] ??= {};
  byChunk[chunk][code] = readFileSync(join(src, file), 'utf8').trim();
  count++;
}
const names = Object.keys(byChunk).sort();
for (const name of names) {
  writeFileSync(join(chunks, `${name}.json`), JSON.stringify(byChunk[name]));
}
writeFileSync(
  join(chunks, 'index.ts'),
  `// Generated by tools/twemoji/generate.mjs; do not edit.
type Chunk = Record<string, string>;

/** Twemoji SVG markup by chunk of the first code point (see generate.mjs). */
export function loadChunk(name: string): Chunk | undefined {
  switch (name) {
${names.map((n) => `    case '${n}':\n      return require('./${n}.json');`).join('\n')}
    default:
      return undefined;
  }
}

export const chunkOf = (code: string) =>
  code.split('-')[0].padStart(5, '0').slice(0, 4);
`,
);
copyFileSync(
  join(process.argv[2], 'LICENSE-GRAPHICS'),
  join(emojiDir, 'TWEMOJI-LICENSE.txt'),
);
console.log(
  `${count} emoji in ${names.length} chunks -> public/twemoji and src/common/emoji/twemoji/`,
);
