#!/usr/bin/env node
// Vendors Twemoji: the SVGs to apps/harbor/public/twemoji/ for the web and
// the 72px PNGs to src/common/emoji/twemoji/ for native, with a require map.
//
//   curl -L -o twemoji.tar.gz https://github.com/jdecked/twemoji/archive/refs/tags/v17.0.3.tar.gz
//   mkdir twemoji && tar -xzf twemoji.tar.gz -C twemoji --strip-components=1 '*/assets/svg/*' '*/assets/72x72/*' '*/LICENSE*'
//   node tools/twemoji/generate.mjs twemoji

import {
  copyFileSync,
  mkdirSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const app = join(root, 'apps', 'harbor');
const src = process.argv[2];
const web = join(app, 'public', 'twemoji');
const emojiDir = join(app, 'src', 'common', 'emoji');
const native = join(emojiDir, 'twemoji');

rmSync(web, { recursive: true, force: true });
mkdirSync(web, { recursive: true });
for (const file of readdirSync(join(src, 'assets', 'svg'))) {
  if (file.endsWith('.svg'))
    copyFileSync(join(src, 'assets', 'svg', file), join(web, file));
}

rmSync(native, { recursive: true, force: true });
mkdirSync(join(native, 'png'), { recursive: true });
const codes = [];
for (const file of readdirSync(join(src, 'assets', '72x72')).sort()) {
  if (!file.endsWith('.png')) continue;
  copyFileSync(join(src, 'assets', '72x72', file), join(native, 'png', file));
  codes.push(file.slice(0, -4));
}
writeFileSync(
  join(native, 'index.ts'),
  `// Generated by tools/twemoji/generate.mjs; do not edit.
import type { ImageRequireSource } from 'react-native';

/** Twemoji PNGs by code (see \`twemojiCode\`). */
export const TWEMOJI: Record<string, ImageRequireSource> = {
${codes.map((c) => `  '${c}': require('./png/${c}.png'),`).join('\n')}
};
`,
);
copyFileSync(
  join(src, 'LICENSE-GRAPHICS'),
  join(emojiDir, 'TWEMOJI-LICENSE.txt'),
);
console.log(
  `${codes.length} emoji -> public/twemoji (svg) and src/common/emoji/twemoji (png)`,
);
