// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { Weapon } from '../../my-game/sample/weapon.js';


export enum Equipment {
  NONE = 0,
  Weapon = 1
}

export function unionToEquipment(
  type: Equipment,
  accessor: (obj:Weapon) => Weapon|null
): Weapon|null {
  switch(Equipment[type]) {
    case 'NONE': return null; 
    case 'Weapon': return accessor(new Weapon())! as Weapon;
    default: return null;
  }
}

export function unionListToEquipment(
  type: Equipment, 
  accessor: (index: number, obj:Weapon) => Weapon|null, 
  index: number
): Weapon|null {
  switch(Equipment[type]) {
    case 'NONE': return null; 
    case 'Weapon': return accessor(index, new Weapon())! as Weapon;
    default: return null;
  }
}
