FROM gcr.io/kaniko-project/executor:debug
LABEL Organization="https://console.cloud.google.com/gcr/images/kaniko-project/global/debug"
LABEL OS="Alpine"
LABEL LICENSE="Apache License 2.0"
LABEL LICENSE_URL="https://github.com/GoogleContainerTools/kaniko/blob/main/LICENSE"