// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/events.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { AttributedTo } from "./content";
import { PageInfo } from "./common";
import { PageParams } from "./common";
import { Blob } from "./content";
import { PublicKey } from "./keypair";
import { SerializedContent } from "./content";
import { ContentDigest } from "./common";
import { EventKey } from "./event_key";
/**
 * Contains the sequences (of the same event collection) that the current KeyPair is aware of.
 * The order of the sequences is determined by the keys listed in the relevant identity document:
 * The rotation keys first and then the signing keys, with duplicates skipped when they appear again.
 * Use `Identity::deduplicated_keys()` to get the keys in this order.
 *
 * @generated from protobuf message polycentric.v2.VectorClock
 */
export interface VectorClock {
    /**
     * @generated from protobuf field: repeated uint64 sequence = 1
     */
    sequence: bigint[];
}
/**
 * The application that authored an event.
 *
 * @generated from protobuf message polycentric.v2.Application
 */
export interface Application {
    /**
     * Human-readable name, e.g. "Harbor".
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * Reverse-DNS package or bundle identifier, e.g. "org.futo.polycentric".
     *
     * @generated from protobuf field: string id = 2
     */
    id: string;
    /**
     * Version of the application, e.g. "1.2.0".
     *
     * @generated from protobuf field: string version = 3
     */
    version: string;
    /**
     * Website of the application, e.g. "https://harbor.social".
     *
     * @generated from protobuf field: string url = 4
     */
    url: string;
}
/**
 * Event messages reference, but do not include, content
 *
 * @generated from protobuf message polycentric.v2.Event
 */
export interface Event {
    /**
     * Key for the event
     *
     * @generated from protobuf field: polycentric.v2.EventKey key = 1
     */
    key?: EventKey;
    /**
     * Reference to the sequence, of the Identity Collection (1), that holds the identity document
     *
     * @generated from protobuf field: uint64 identity_sequence = 2
     */
    identitySequence: bigint;
    /**
     * Vector clock
     *
     * @generated from protobuf field: polycentric.v2.VectorClock vector_clock = 3
     */
    vectorClock?: VectorClock;
    /**
     * Signature of the previous event signed by the same key. Assists in creating
     * immutable collections.
     *
     * @generated from protobuf field: bytes previous_signature = 4
     */
    previousSignature: Uint8Array;
    /**
     * Digest of the content
     *
     * @generated from protobuf field: polycentric.v2.ContentDigest content_digest = 6
     */
    contentDigest?: ContentDigest;
    /**
     * Timestamp, in milliseconds, of when the event was created
     *
     * @generated from protobuf field: uint64 created_at = 7
     */
    createdAt: bigint;
    /**
     * RFC 6962 Merkle root over this signer's prior signatures in this collection
     * (leaf_count = key.sequence - 1). Lets later events attest to the writer's
     * history; consumed by EventProof for membership verification.
     *
     * @generated from protobuf field: bytes previous_root = 8
     */
    previousRoot: Uint8Array;
    /**
     * The application that created the event. Absent when unknown.
     *
     * @generated from protobuf field: optional polycentric.v2.Application application = 9
     */
    application?: Application;
}
/**
 * @generated from protobuf message polycentric.v2.SignedEvent
 */
export interface SignedEvent {
    /**
     * Signature of events_bytes below (not the Event message)
     *
     * @generated from protobuf field: bytes signature = 1
     */
    signature: Uint8Array;
    /**
     * Serialized representation of the Event message that is signed against
     *
     * @generated from protobuf field: bytes event_bytes = 2
     */
    eventBytes: Uint8Array;
}
/**
 * Bundle of the SignedEvent and SerializedContent messages
 * We use SerializedContent so that the checksum of the content
 * can be verified
 *
 * @generated from protobuf message polycentric.v2.EventBundle
 */
export interface EventBundle {
    /**
     * @generated from protobuf field: polycentric.v2.SignedEvent signed_event = 1
     */
    signedEvent?: SignedEvent;
    /**
     * @generated from protobuf field: optional polycentric.v2.SerializedContent serialized_content = 2
     */
    serializedContent?: SerializedContent;
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventProof event_proofs = 3
     */
    eventProofs: EventProof[];
    /**
     * @generated from protobuf field: optional polycentric.v2.EventMetadata meta = 4
     */
    meta?: EventMetadata;
}
/**
 * Merkle inclusion proof: the SignedEvent in this bundle is the leaf at
 * `leaf_index` in the tree rooted at the `EventProofTarget` identified by
 * `target_signature`.
 *
 * @generated from protobuf message polycentric.v2.EventProof
 */
export interface EventProof {
    /**
     * @generated from protobuf field: bytes target_signature = 1
     */
    targetSignature: Uint8Array;
    /**
     * Canonical position of this event in the target's tree.
     *
     * @generated from protobuf field: uint64 leaf_index = 2
     */
    leafIndex: bigint;
    /**
     * RFC 6962 audit path: sibling hashes from leaf toward root.
     *
     * @generated from protobuf field: repeated bytes audit_path = 3
     */
    auditPath: Uint8Array[];
}
/**
 * Optional helper data that servers can include to help clients better present
 * information to users.
 *
 * @generated from protobuf message polycentric.v2.EventMetadata
 */
export interface EventMetadata {
    /**
     * This server's estimate for how many replies a post has.
     *
     * @generated from protobuf field: optional int32 reply_count = 1
     */
    replyCount?: number;
    /**
     * This server's estimate for the total number of reactions a post has.
     *
     * @generated from protobuf field: optional int32 reaction_count = 2
     */
    reactionCount?: number;
    /**
     * This server's estimate for the total number of positive reactions a post has.
     *
     * @generated from protobuf field: optional int32 upvote_count = 3
     */
    upvoteCount?: number;
    /**
     * This server's estimate for the total number of negative reactions a post has.
     *
     * @generated from protobuf field: optional int32 downvote_count = 4
     */
    downvoteCount?: number;
    /**
     * This server's estimate for the count for each reaction type a post has.
     *
     * @generated from protobuf field: repeated polycentric.v2.ReactionTally emoji_reactions = 5
     */
    emojiReactions: ReactionTally[];
}
/**
 * Conveys the number of times a specific reaction was given.
 *
 * @generated from protobuf message polycentric.v2.ReactionTally
 */
export interface ReactionTally {
    /**
     * @generated from protobuf field: string emoji = 1
     */
    emoji: string;
    /**
     * @generated from protobuf field: bool positive = 2
     */
    positive: boolean;
    /**
     * @generated from protobuf field: int32 count = 3
     */
    count: number;
}
/**
 * Hints are additional events that the server provides that may be
 * useful to the client and avoid additional network requests.
 * For example, a reply to post event could return the root/parent posts along with the
 * most recent profile event
 *
 * @generated from protobuf message polycentric.v2.EventHint
 */
export interface EventHint {
    /**
     * @generated from protobuf field: polycentric.v2.EventBundle event_bundle = 1
     */
    eventBundle?: EventBundle;
}
/**
 * @generated from protobuf message polycentric.v2.ListEventsFilters
 */
export interface ListEventsFilters {
    /**
     * Collection to filter events by
     *
     * @generated from protobuf field: optional int32 collection = 1
     */
    collection?: number;
    /**
     * Identity key to filter events by
     *
     * @generated from protobuf field: optional string identity = 2
     */
    identity?: string;
    /**
     * Filter events to those signed by this public key
     *
     * @generated from protobuf field: optional polycentric.v2.PublicKey signed_by = 3
     */
    signedBy?: PublicKey;
    /**
     * Return sequences greater than
     *
     * @generated from protobuf field: optional int64 sequence_gt = 4
     */
    sequenceGt?: bigint;
    /**
     * Return sequences less than
     *
     * @generated from protobuf field: optional int64 sequence_lt = 5
     */
    sequenceLt?: bigint;
    /**
     * When an event matches a head's identity, collection, and signer,
     * only return it if its sequence number is higher than the head
     *
     * @generated from protobuf field: repeated polycentric.v2.EventKey heads = 6
     */
    heads: EventKey[];
}
/**
 * @generated from protobuf message polycentric.v2.ListEventsRequest
 */
export interface ListEventsRequest {
    /**
     * Filters
     *
     * @generated from protobuf field: optional polycentric.v2.ListEventsFilters filters = 1
     */
    filters?: ListEventsFilters;
    /**
     * Max number of events to return
     *
     * @generated from protobuf field: optional int32 size = 2
     */
    size?: number;
}
/**
 * @generated from protobuf message polycentric.v2.ListEventsResponse
 */
export interface ListEventsResponse {
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventBundle event_bundles = 1
     */
    eventBundles: EventBundle[];
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventHint event_hints = 2
     */
    eventHints: EventHint[];
}
/**
 * @generated from protobuf message polycentric.v2.PutEventsRequest
 */
export interface PutEventsRequest {
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventBundle event_bundles = 1
     */
    eventBundles: EventBundle[];
}
/**
 * Per-event failure reported by PutEvents. The call as a whole still
 * succeeds — these entries are diagnostic for events the server
 * skipped.
 *
 * @generated from protobuf message polycentric.v2.PutEventError
 */
export interface PutEventError {
    /**
     * Index of the failed entry in PutEventsRequest.event_bundles.
     *
     * @generated from protobuf field: uint32 event_bundle_index = 1
     */
    eventBundleIndex: number;
    /**
     * Human-readable reason mirroring the gRPC Status ingest would
     * otherwise have returned for this event in isolation.
     *
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message polycentric.v2.PutEventsResponse
 */
export interface PutEventsResponse {
    /**
     * One entry per event the server could not store. Empty when every
     * event in the request was accepted.
     *
     * @generated from protobuf field: repeated polycentric.v2.PutEventError errors = 1
     */
    errors: PutEventError[];
    /**
     * Blobs referenced by the events that the server does not have.
     * Client should upload these.
     *
     * @generated from protobuf field: repeated polycentric.v2.Blob requested_blobs = 2
     */
    requestedBlobs: Blob[];
}
/**
 * @generated from protobuf message polycentric.v2.ListHeadsRequest
 */
export interface ListHeadsRequest {
    /**
     * @generated from protobuf field: string identity = 1
     */
    identity: string;
}
/**
 * @generated from protobuf message polycentric.v2.ListHeadsResponse
 */
export interface ListHeadsResponse {
    /**
     * Each event key represents the greatest sequence number
     * with the same (identity, public key, collection) known by this server
     *
     * @generated from protobuf field: repeated polycentric.v2.EventKey heads = 1
     */
    heads: EventKey[];
}
/**
 * @generated from protobuf message polycentric.v2.GetReactionsRequest
 */
export interface GetReactionsRequest {
    /**
     * Event key of the event to get reactions for
     *
     * @generated from protobuf field: polycentric.v2.EventKey target = 1
     */
    target?: EventKey;
    /**
     * Return only reactions with this emoji set
     *
     * @generated from protobuf field: optional string emoji_filter = 2
     */
    emojiFilter?: string;
    /**
     * @generated from protobuf field: optional polycentric.v2.PageParams page_params = 3
     */
    pageParams?: PageParams;
}
/**
 * @generated from protobuf message polycentric.v2.GetReactionsResponse
 */
export interface GetReactionsResponse {
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventBundle event_bundles = 1
     */
    eventBundles: EventBundle[];
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventHint event_hints = 2
     */
    eventHints: EventHint[];
    /**
     * @generated from protobuf field: optional polycentric.v2.PageInfo page_info = 3
     */
    pageInfo?: PageInfo;
}
/**
 * @generated from protobuf message polycentric.v2.GetAttributedToReactionCountsRequest
 */
export interface GetAttributedToReactionCountsRequest {
    /**
     * The attributed target (e.g. a video URL) to get reaction counts for.
     *
     * @generated from protobuf field: polycentric.v2.AttributedTo attributed_to = 1
     */
    attributedTo?: AttributedTo;
}
/**
 * @generated from protobuf message polycentric.v2.GetAttributedToReactionCountsResponse
 */
export interface GetAttributedToReactionCountsResponse {
    /**
     * The server's estimate for positive reactions on the target.
     *
     * @generated from protobuf field: int64 upvote_count = 1
     */
    upvoteCount: bigint;
    /**
     * The server's estimate for negative reactions on the target.
     *
     * @generated from protobuf field: int64 downvote_count = 2
     */
    downvoteCount: bigint;
}
// @generated message type with reflection information, may provide speed optimized methods
class VectorClock$Type extends MessageType<VectorClock> {
    constructor() {
        super("polycentric.v2.VectorClock", [
            { no: 1, name: "sequence", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<VectorClock>): VectorClock {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sequence = [];
        if (value !== undefined)
            reflectionMergePartial<VectorClock>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VectorClock): VectorClock {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated uint64 sequence */ 1:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.sequence.push(reader.uint64().toBigInt());
                    else
                        message.sequence.push(reader.uint64().toBigInt());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: VectorClock, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated uint64 sequence = 1; */
        if (message.sequence.length) {
            writer.tag(1, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.sequence.length; i++)
                writer.uint64(message.sequence[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.VectorClock
 */
export const VectorClock = new VectorClock$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Application$Type extends MessageType<Application> {
    constructor() {
        super("polycentric.v2.Application", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Application>): Application {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.id = "";
        message.version = "";
        message.url = "";
        if (value !== undefined)
            reflectionMergePartial<Application>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Application): Application {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string id */ 2:
                    message.id = reader.string();
                    break;
                case /* string version */ 3:
                    message.version = reader.string();
                    break;
                case /* string url */ 4:
                    message.url = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Application, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string id = 2; */
        if (message.id !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.id);
        /* string version = 3; */
        if (message.version !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.version);
        /* string url = 4; */
        if (message.url !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.url);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Application
 */
export const Application = new Application$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Event$Type extends MessageType<Event> {
    constructor() {
        super("polycentric.v2.Event", [
            { no: 1, name: "key", kind: "message", T: () => EventKey },
            { no: 2, name: "identity_sequence", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "vector_clock", kind: "message", T: () => VectorClock },
            { no: 4, name: "previous_signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 6, name: "content_digest", kind: "message", T: () => ContentDigest },
            { no: 7, name: "created_at", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 8, name: "previous_root", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 9, name: "application", kind: "message", T: () => Application }
        ]);
    }
    create(value?: PartialMessage<Event>): Event {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.identitySequence = 0n;
        message.previousSignature = new Uint8Array(0);
        message.createdAt = 0n;
        message.previousRoot = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<Event>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Event): Event {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventKey key */ 1:
                    message.key = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.key);
                    break;
                case /* uint64 identity_sequence */ 2:
                    message.identitySequence = reader.uint64().toBigInt();
                    break;
                case /* polycentric.v2.VectorClock vector_clock */ 3:
                    message.vectorClock = VectorClock.internalBinaryRead(reader, reader.uint32(), options, message.vectorClock);
                    break;
                case /* bytes previous_signature */ 4:
                    message.previousSignature = reader.bytes();
                    break;
                case /* polycentric.v2.ContentDigest content_digest */ 6:
                    message.contentDigest = ContentDigest.internalBinaryRead(reader, reader.uint32(), options, message.contentDigest);
                    break;
                case /* uint64 created_at */ 7:
                    message.createdAt = reader.uint64().toBigInt();
                    break;
                case /* bytes previous_root */ 8:
                    message.previousRoot = reader.bytes();
                    break;
                case /* optional polycentric.v2.Application application */ 9:
                    message.application = Application.internalBinaryRead(reader, reader.uint32(), options, message.application);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Event, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventKey key = 1; */
        if (message.key)
            EventKey.internalBinaryWrite(message.key, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* uint64 identity_sequence = 2; */
        if (message.identitySequence !== 0n)
            writer.tag(2, WireType.Varint).uint64(message.identitySequence);
        /* polycentric.v2.VectorClock vector_clock = 3; */
        if (message.vectorClock)
            VectorClock.internalBinaryWrite(message.vectorClock, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* bytes previous_signature = 4; */
        if (message.previousSignature.length)
            writer.tag(4, WireType.LengthDelimited).bytes(message.previousSignature);
        /* polycentric.v2.ContentDigest content_digest = 6; */
        if (message.contentDigest)
            ContentDigest.internalBinaryWrite(message.contentDigest, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* uint64 created_at = 7; */
        if (message.createdAt !== 0n)
            writer.tag(7, WireType.Varint).uint64(message.createdAt);
        /* bytes previous_root = 8; */
        if (message.previousRoot.length)
            writer.tag(8, WireType.LengthDelimited).bytes(message.previousRoot);
        /* optional polycentric.v2.Application application = 9; */
        if (message.application)
            Application.internalBinaryWrite(message.application, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Event
 */
export const Event = new Event$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SignedEvent$Type extends MessageType<SignedEvent> {
    constructor() {
        super("polycentric.v2.SignedEvent", [
            { no: 1, name: "signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "event_bytes", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<SignedEvent>): SignedEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.signature = new Uint8Array(0);
        message.eventBytes = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<SignedEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SignedEvent): SignedEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes signature */ 1:
                    message.signature = reader.bytes();
                    break;
                case /* bytes event_bytes */ 2:
                    message.eventBytes = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SignedEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes signature = 1; */
        if (message.signature.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.signature);
        /* bytes event_bytes = 2; */
        if (message.eventBytes.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.eventBytes);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SignedEvent
 */
export const SignedEvent = new SignedEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EventBundle$Type extends MessageType<EventBundle> {
    constructor() {
        super("polycentric.v2.EventBundle", [
            { no: 1, name: "signed_event", kind: "message", T: () => SignedEvent },
            { no: 2, name: "serialized_content", kind: "message", T: () => SerializedContent },
            { no: 3, name: "event_proofs", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventProof },
            { no: 4, name: "meta", kind: "message", T: () => EventMetadata }
        ]);
    }
    create(value?: PartialMessage<EventBundle>): EventBundle {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventProofs = [];
        if (value !== undefined)
            reflectionMergePartial<EventBundle>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EventBundle): EventBundle {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.SignedEvent signed_event */ 1:
                    message.signedEvent = SignedEvent.internalBinaryRead(reader, reader.uint32(), options, message.signedEvent);
                    break;
                case /* optional polycentric.v2.SerializedContent serialized_content */ 2:
                    message.serializedContent = SerializedContent.internalBinaryRead(reader, reader.uint32(), options, message.serializedContent);
                    break;
                case /* repeated polycentric.v2.EventProof event_proofs */ 3:
                    message.eventProofs.push(EventProof.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional polycentric.v2.EventMetadata meta */ 4:
                    message.meta = EventMetadata.internalBinaryRead(reader, reader.uint32(), options, message.meta);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EventBundle, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.SignedEvent signed_event = 1; */
        if (message.signedEvent)
            SignedEvent.internalBinaryWrite(message.signedEvent, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional polycentric.v2.SerializedContent serialized_content = 2; */
        if (message.serializedContent)
            SerializedContent.internalBinaryWrite(message.serializedContent, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.EventProof event_proofs = 3; */
        for (let i = 0; i < message.eventProofs.length; i++)
            EventProof.internalBinaryWrite(message.eventProofs[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional polycentric.v2.EventMetadata meta = 4; */
        if (message.meta)
            EventMetadata.internalBinaryWrite(message.meta, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.EventBundle
 */
export const EventBundle = new EventBundle$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EventProof$Type extends MessageType<EventProof> {
    constructor() {
        super("polycentric.v2.EventProof", [
            { no: 1, name: "target_signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "leaf_index", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "audit_path", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<EventProof>): EventProof {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.targetSignature = new Uint8Array(0);
        message.leafIndex = 0n;
        message.auditPath = [];
        if (value !== undefined)
            reflectionMergePartial<EventProof>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EventProof): EventProof {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes target_signature */ 1:
                    message.targetSignature = reader.bytes();
                    break;
                case /* uint64 leaf_index */ 2:
                    message.leafIndex = reader.uint64().toBigInt();
                    break;
                case /* repeated bytes audit_path */ 3:
                    message.auditPath.push(reader.bytes());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EventProof, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes target_signature = 1; */
        if (message.targetSignature.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.targetSignature);
        /* uint64 leaf_index = 2; */
        if (message.leafIndex !== 0n)
            writer.tag(2, WireType.Varint).uint64(message.leafIndex);
        /* repeated bytes audit_path = 3; */
        for (let i = 0; i < message.auditPath.length; i++)
            writer.tag(3, WireType.LengthDelimited).bytes(message.auditPath[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.EventProof
 */
export const EventProof = new EventProof$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EventMetadata$Type extends MessageType<EventMetadata> {
    constructor() {
        super("polycentric.v2.EventMetadata", [
            { no: 1, name: "reply_count", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "reaction_count", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "upvote_count", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "downvote_count", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "emoji_reactions", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ReactionTally }
        ]);
    }
    create(value?: PartialMessage<EventMetadata>): EventMetadata {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.emojiReactions = [];
        if (value !== undefined)
            reflectionMergePartial<EventMetadata>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EventMetadata): EventMetadata {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional int32 reply_count */ 1:
                    message.replyCount = reader.int32();
                    break;
                case /* optional int32 reaction_count */ 2:
                    message.reactionCount = reader.int32();
                    break;
                case /* optional int32 upvote_count */ 3:
                    message.upvoteCount = reader.int32();
                    break;
                case /* optional int32 downvote_count */ 4:
                    message.downvoteCount = reader.int32();
                    break;
                case /* repeated polycentric.v2.ReactionTally emoji_reactions */ 5:
                    message.emojiReactions.push(ReactionTally.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EventMetadata, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional int32 reply_count = 1; */
        if (message.replyCount !== undefined)
            writer.tag(1, WireType.Varint).int32(message.replyCount);
        /* optional int32 reaction_count = 2; */
        if (message.reactionCount !== undefined)
            writer.tag(2, WireType.Varint).int32(message.reactionCount);
        /* optional int32 upvote_count = 3; */
        if (message.upvoteCount !== undefined)
            writer.tag(3, WireType.Varint).int32(message.upvoteCount);
        /* optional int32 downvote_count = 4; */
        if (message.downvoteCount !== undefined)
            writer.tag(4, WireType.Varint).int32(message.downvoteCount);
        /* repeated polycentric.v2.ReactionTally emoji_reactions = 5; */
        for (let i = 0; i < message.emojiReactions.length; i++)
            ReactionTally.internalBinaryWrite(message.emojiReactions[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.EventMetadata
 */
export const EventMetadata = new EventMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReactionTally$Type extends MessageType<ReactionTally> {
    constructor() {
        super("polycentric.v2.ReactionTally", [
            { no: 1, name: "emoji", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "positive", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ReactionTally>): ReactionTally {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.emoji = "";
        message.positive = false;
        message.count = 0;
        if (value !== undefined)
            reflectionMergePartial<ReactionTally>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReactionTally): ReactionTally {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string emoji */ 1:
                    message.emoji = reader.string();
                    break;
                case /* bool positive */ 2:
                    message.positive = reader.bool();
                    break;
                case /* int32 count */ 3:
                    message.count = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReactionTally, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string emoji = 1; */
        if (message.emoji !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.emoji);
        /* bool positive = 2; */
        if (message.positive !== false)
            writer.tag(2, WireType.Varint).bool(message.positive);
        /* int32 count = 3; */
        if (message.count !== 0)
            writer.tag(3, WireType.Varint).int32(message.count);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ReactionTally
 */
export const ReactionTally = new ReactionTally$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EventHint$Type extends MessageType<EventHint> {
    constructor() {
        super("polycentric.v2.EventHint", [
            { no: 1, name: "event_bundle", kind: "message", T: () => EventBundle }
        ]);
    }
    create(value?: PartialMessage<EventHint>): EventHint {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<EventHint>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EventHint): EventHint {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventBundle event_bundle */ 1:
                    message.eventBundle = EventBundle.internalBinaryRead(reader, reader.uint32(), options, message.eventBundle);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EventHint, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventBundle event_bundle = 1; */
        if (message.eventBundle)
            EventBundle.internalBinaryWrite(message.eventBundle, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.EventHint
 */
export const EventHint = new EventHint$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListEventsFilters$Type extends MessageType<ListEventsFilters> {
    constructor() {
        super("polycentric.v2.ListEventsFilters", [
            { no: 1, name: "collection", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "identity", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "signed_by", kind: "message", T: () => PublicKey },
            { no: 4, name: "sequence_gt", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "sequence_lt", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 6, name: "heads", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventKey }
        ]);
    }
    create(value?: PartialMessage<ListEventsFilters>): ListEventsFilters {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.heads = [];
        if (value !== undefined)
            reflectionMergePartial<ListEventsFilters>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListEventsFilters): ListEventsFilters {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional int32 collection */ 1:
                    message.collection = reader.int32();
                    break;
                case /* optional string identity */ 2:
                    message.identity = reader.string();
                    break;
                case /* optional polycentric.v2.PublicKey signed_by */ 3:
                    message.signedBy = PublicKey.internalBinaryRead(reader, reader.uint32(), options, message.signedBy);
                    break;
                case /* optional int64 sequence_gt */ 4:
                    message.sequenceGt = reader.int64().toBigInt();
                    break;
                case /* optional int64 sequence_lt */ 5:
                    message.sequenceLt = reader.int64().toBigInt();
                    break;
                case /* repeated polycentric.v2.EventKey heads */ 6:
                    message.heads.push(EventKey.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListEventsFilters, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional int32 collection = 1; */
        if (message.collection !== undefined)
            writer.tag(1, WireType.Varint).int32(message.collection);
        /* optional string identity = 2; */
        if (message.identity !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.identity);
        /* optional polycentric.v2.PublicKey signed_by = 3; */
        if (message.signedBy)
            PublicKey.internalBinaryWrite(message.signedBy, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional int64 sequence_gt = 4; */
        if (message.sequenceGt !== undefined)
            writer.tag(4, WireType.Varint).int64(message.sequenceGt);
        /* optional int64 sequence_lt = 5; */
        if (message.sequenceLt !== undefined)
            writer.tag(5, WireType.Varint).int64(message.sequenceLt);
        /* repeated polycentric.v2.EventKey heads = 6; */
        for (let i = 0; i < message.heads.length; i++)
            EventKey.internalBinaryWrite(message.heads[i], writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ListEventsFilters
 */
export const ListEventsFilters = new ListEventsFilters$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListEventsRequest$Type extends MessageType<ListEventsRequest> {
    constructor() {
        super("polycentric.v2.ListEventsRequest", [
            { no: 1, name: "filters", kind: "message", T: () => ListEventsFilters },
            { no: 2, name: "size", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ListEventsRequest>): ListEventsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListEventsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListEventsRequest): ListEventsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional polycentric.v2.ListEventsFilters filters */ 1:
                    message.filters = ListEventsFilters.internalBinaryRead(reader, reader.uint32(), options, message.filters);
                    break;
                case /* optional int32 size */ 2:
                    message.size = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListEventsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional polycentric.v2.ListEventsFilters filters = 1; */
        if (message.filters)
            ListEventsFilters.internalBinaryWrite(message.filters, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional int32 size = 2; */
        if (message.size !== undefined)
            writer.tag(2, WireType.Varint).int32(message.size);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ListEventsRequest
 */
export const ListEventsRequest = new ListEventsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListEventsResponse$Type extends MessageType<ListEventsResponse> {
    constructor() {
        super("polycentric.v2.ListEventsResponse", [
            { no: 1, name: "event_bundles", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventBundle },
            { no: 2, name: "event_hints", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventHint }
        ]);
    }
    create(value?: PartialMessage<ListEventsResponse>): ListEventsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventBundles = [];
        message.eventHints = [];
        if (value !== undefined)
            reflectionMergePartial<ListEventsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListEventsResponse): ListEventsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.EventBundle event_bundles */ 1:
                    message.eventBundles.push(EventBundle.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated polycentric.v2.EventHint event_hints */ 2:
                    message.eventHints.push(EventHint.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListEventsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.EventBundle event_bundles = 1; */
        for (let i = 0; i < message.eventBundles.length; i++)
            EventBundle.internalBinaryWrite(message.eventBundles[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.EventHint event_hints = 2; */
        for (let i = 0; i < message.eventHints.length; i++)
            EventHint.internalBinaryWrite(message.eventHints[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ListEventsResponse
 */
export const ListEventsResponse = new ListEventsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PutEventsRequest$Type extends MessageType<PutEventsRequest> {
    constructor() {
        super("polycentric.v2.PutEventsRequest", [
            { no: 1, name: "event_bundles", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventBundle }
        ]);
    }
    create(value?: PartialMessage<PutEventsRequest>): PutEventsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventBundles = [];
        if (value !== undefined)
            reflectionMergePartial<PutEventsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PutEventsRequest): PutEventsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.EventBundle event_bundles */ 1:
                    message.eventBundles.push(EventBundle.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PutEventsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.EventBundle event_bundles = 1; */
        for (let i = 0; i < message.eventBundles.length; i++)
            EventBundle.internalBinaryWrite(message.eventBundles[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PutEventsRequest
 */
export const PutEventsRequest = new PutEventsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PutEventError$Type extends MessageType<PutEventError> {
    constructor() {
        super("polycentric.v2.PutEventError", [
            { no: 1, name: "event_bundle_index", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PutEventError>): PutEventError {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventBundleIndex = 0;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<PutEventError>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PutEventError): PutEventError {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 event_bundle_index */ 1:
                    message.eventBundleIndex = reader.uint32();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PutEventError, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 event_bundle_index = 1; */
        if (message.eventBundleIndex !== 0)
            writer.tag(1, WireType.Varint).uint32(message.eventBundleIndex);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PutEventError
 */
export const PutEventError = new PutEventError$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PutEventsResponse$Type extends MessageType<PutEventsResponse> {
    constructor() {
        super("polycentric.v2.PutEventsResponse", [
            { no: 1, name: "errors", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PutEventError },
            { no: 2, name: "requested_blobs", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Blob }
        ]);
    }
    create(value?: PartialMessage<PutEventsResponse>): PutEventsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.errors = [];
        message.requestedBlobs = [];
        if (value !== undefined)
            reflectionMergePartial<PutEventsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PutEventsResponse): PutEventsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.PutEventError errors */ 1:
                    message.errors.push(PutEventError.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated polycentric.v2.Blob requested_blobs */ 2:
                    message.requestedBlobs.push(Blob.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PutEventsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.PutEventError errors = 1; */
        for (let i = 0; i < message.errors.length; i++)
            PutEventError.internalBinaryWrite(message.errors[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.Blob requested_blobs = 2; */
        for (let i = 0; i < message.requestedBlobs.length; i++)
            Blob.internalBinaryWrite(message.requestedBlobs[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PutEventsResponse
 */
export const PutEventsResponse = new PutEventsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListHeadsRequest$Type extends MessageType<ListHeadsRequest> {
    constructor() {
        super("polycentric.v2.ListHeadsRequest", [
            { no: 1, name: "identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListHeadsRequest>): ListHeadsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.identity = "";
        if (value !== undefined)
            reflectionMergePartial<ListHeadsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListHeadsRequest): ListHeadsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string identity */ 1:
                    message.identity = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListHeadsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string identity = 1; */
        if (message.identity !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.identity);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ListHeadsRequest
 */
export const ListHeadsRequest = new ListHeadsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListHeadsResponse$Type extends MessageType<ListHeadsResponse> {
    constructor() {
        super("polycentric.v2.ListHeadsResponse", [
            { no: 1, name: "heads", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventKey }
        ]);
    }
    create(value?: PartialMessage<ListHeadsResponse>): ListHeadsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.heads = [];
        if (value !== undefined)
            reflectionMergePartial<ListHeadsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListHeadsResponse): ListHeadsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.EventKey heads */ 1:
                    message.heads.push(EventKey.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListHeadsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.EventKey heads = 1; */
        for (let i = 0; i < message.heads.length; i++)
            EventKey.internalBinaryWrite(message.heads[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ListHeadsResponse
 */
export const ListHeadsResponse = new ListHeadsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetReactionsRequest$Type extends MessageType<GetReactionsRequest> {
    constructor() {
        super("polycentric.v2.GetReactionsRequest", [
            { no: 1, name: "target", kind: "message", T: () => EventKey },
            { no: 2, name: "emoji_filter", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "page_params", kind: "message", T: () => PageParams }
        ]);
    }
    create(value?: PartialMessage<GetReactionsRequest>): GetReactionsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetReactionsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetReactionsRequest): GetReactionsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventKey target */ 1:
                    message.target = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.target);
                    break;
                case /* optional string emoji_filter */ 2:
                    message.emojiFilter = reader.string();
                    break;
                case /* optional polycentric.v2.PageParams page_params */ 3:
                    message.pageParams = PageParams.internalBinaryRead(reader, reader.uint32(), options, message.pageParams);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetReactionsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventKey target = 1; */
        if (message.target)
            EventKey.internalBinaryWrite(message.target, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional string emoji_filter = 2; */
        if (message.emojiFilter !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.emojiFilter);
        /* optional polycentric.v2.PageParams page_params = 3; */
        if (message.pageParams)
            PageParams.internalBinaryWrite(message.pageParams, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetReactionsRequest
 */
export const GetReactionsRequest = new GetReactionsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetReactionsResponse$Type extends MessageType<GetReactionsResponse> {
    constructor() {
        super("polycentric.v2.GetReactionsResponse", [
            { no: 1, name: "event_bundles", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventBundle },
            { no: 2, name: "event_hints", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventHint },
            { no: 3, name: "page_info", kind: "message", T: () => PageInfo }
        ]);
    }
    create(value?: PartialMessage<GetReactionsResponse>): GetReactionsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventBundles = [];
        message.eventHints = [];
        if (value !== undefined)
            reflectionMergePartial<GetReactionsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetReactionsResponse): GetReactionsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.EventBundle event_bundles */ 1:
                    message.eventBundles.push(EventBundle.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated polycentric.v2.EventHint event_hints */ 2:
                    message.eventHints.push(EventHint.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional polycentric.v2.PageInfo page_info */ 3:
                    message.pageInfo = PageInfo.internalBinaryRead(reader, reader.uint32(), options, message.pageInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetReactionsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.EventBundle event_bundles = 1; */
        for (let i = 0; i < message.eventBundles.length; i++)
            EventBundle.internalBinaryWrite(message.eventBundles[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.EventHint event_hints = 2; */
        for (let i = 0; i < message.eventHints.length; i++)
            EventHint.internalBinaryWrite(message.eventHints[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional polycentric.v2.PageInfo page_info = 3; */
        if (message.pageInfo)
            PageInfo.internalBinaryWrite(message.pageInfo, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetReactionsResponse
 */
export const GetReactionsResponse = new GetReactionsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAttributedToReactionCountsRequest$Type extends MessageType<GetAttributedToReactionCountsRequest> {
    constructor() {
        super("polycentric.v2.GetAttributedToReactionCountsRequest", [
            { no: 1, name: "attributed_to", kind: "message", T: () => AttributedTo }
        ]);
    }
    create(value?: PartialMessage<GetAttributedToReactionCountsRequest>): GetAttributedToReactionCountsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetAttributedToReactionCountsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAttributedToReactionCountsRequest): GetAttributedToReactionCountsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.AttributedTo attributed_to */ 1:
                    message.attributedTo = AttributedTo.internalBinaryRead(reader, reader.uint32(), options, message.attributedTo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAttributedToReactionCountsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.AttributedTo attributed_to = 1; */
        if (message.attributedTo)
            AttributedTo.internalBinaryWrite(message.attributedTo, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetAttributedToReactionCountsRequest
 */
export const GetAttributedToReactionCountsRequest = new GetAttributedToReactionCountsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAttributedToReactionCountsResponse$Type extends MessageType<GetAttributedToReactionCountsResponse> {
    constructor() {
        super("polycentric.v2.GetAttributedToReactionCountsResponse", [
            { no: 1, name: "upvote_count", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "downvote_count", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<GetAttributedToReactionCountsResponse>): GetAttributedToReactionCountsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.upvoteCount = 0n;
        message.downvoteCount = 0n;
        if (value !== undefined)
            reflectionMergePartial<GetAttributedToReactionCountsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAttributedToReactionCountsResponse): GetAttributedToReactionCountsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 upvote_count */ 1:
                    message.upvoteCount = reader.int64().toBigInt();
                    break;
                case /* int64 downvote_count */ 2:
                    message.downvoteCount = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAttributedToReactionCountsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 upvote_count = 1; */
        if (message.upvoteCount !== 0n)
            writer.tag(1, WireType.Varint).int64(message.upvoteCount);
        /* int64 downvote_count = 2; */
        if (message.downvoteCount !== 0n)
            writer.tag(2, WireType.Varint).int64(message.downvoteCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetAttributedToReactionCountsResponse
 */
export const GetAttributedToReactionCountsResponse = new GetAttributedToReactionCountsResponse$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.EventSyncService
 */
export const EventSyncService = new ServiceType("polycentric.v2.EventSyncService", [
    { name: "ListEvents", options: {}, I: ListEventsRequest, O: ListEventsResponse },
    { name: "PutEvents", options: {}, I: PutEventsRequest, O: PutEventsResponse },
    { name: "ListHeads", options: {}, I: ListHeadsRequest, O: ListHeadsResponse },
    { name: "GetReactions", options: {}, I: GetReactionsRequest, O: GetReactionsResponse },
    { name: "GetAttributedToReactionCounts", options: {}, I: GetAttributedToReactionCountsRequest, O: GetAttributedToReactionCountsResponse }
]);
