// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/feeds.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { AttributedTo } from "./content";
import { EventKey } from "./event_key";
import { PageInfo } from "./common";
import { EventHint } from "./events";
import { EventBundle } from "./events";
import { SortPostsBy } from "./search";
import { PageParams } from "./common";
/**
 * @generated from protobuf message polycentric.v2.GetIdentityFeedRequest
 */
export interface GetIdentityFeedRequest {
    /**
     * Identity to return the posts of
     *
     * @generated from protobuf field: string identity = 1
     */
    identity: string;
    /**
     * @generated from protobuf field: optional polycentric.v2.PageParams page_params = 2
     */
    pageParams?: PageParams;
    /**
     * Label values for which the requester does not want to see content
     *
     * @generated from protobuf field: repeated string omit_labels = 3
     */
    omitLabels: string[];
}
/**
 * @generated from protobuf message polycentric.v2.GetFollowingFeedRequest
 */
export interface GetFollowingFeedRequest {
    /**
     * Identity of the follower to return the feed for
     *
     * @generated from protobuf field: string follower_identity = 1
     */
    followerIdentity: string;
    /**
     * @generated from protobuf field: optional polycentric.v2.PageParams page_params = 2
     */
    pageParams?: PageParams;
    /**
     * Label values for which the requester does not want to see content
     *
     * @generated from protobuf field: repeated string omit_labels = 3
     */
    omitLabels: string[];
    /**
     * @generated from protobuf field: optional polycentric.v2.SortPostsBy sort_by = 4
     */
    sortBy?: SortPostsBy;
}
/**
 * @generated from protobuf message polycentric.v2.GetExploreFeedRequest
 */
export interface GetExploreFeedRequest {
    /**
     * Identity of the caller to return relevant posts for
     *
     * @generated from protobuf field: optional string identity = 1
     */
    identity?: string;
    /**
     * @generated from protobuf field: optional polycentric.v2.PageParams page_params = 2
     */
    pageParams?: PageParams;
    /**
     * Label values for which the requester does not want to see content
     *
     * @generated from protobuf field: repeated string omit_labels = 3
     */
    omitLabels: string[];
    /**
     * @generated from protobuf field: optional polycentric.v2.SortPostsBy sort_by = 4
     */
    sortBy?: SortPostsBy;
}
/**
 * @generated from protobuf message polycentric.v2.GetFeedResponse
 */
export interface GetFeedResponse {
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventBundle event_bundles = 1
     */
    eventBundles: EventBundle[];
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventHint event_hints = 2
     */
    eventHints: EventHint[];
    /**
     * @generated from protobuf field: optional polycentric.v2.PageInfo page_info = 3
     */
    pageInfo?: PageInfo;
}
/**
 * @generated from protobuf message polycentric.v2.GetPostThreadResponse
 */
export interface GetPostThreadResponse {
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventBundle thread = 1
     */
    thread: EventBundle[];
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventHint event_hints = 2
     */
    eventHints: EventHint[];
}
/**
 * @generated from protobuf message polycentric.v2.GetPostRequest
 */
export interface GetPostRequest {
    /**
     * @generated from protobuf field: polycentric.v2.EventKey event_key = 1
     */
    eventKey?: EventKey;
}
/**
 * @generated from protobuf message polycentric.v2.GetPostResponse
 */
export interface GetPostResponse {
    /**
     * @generated from protobuf field: optional polycentric.v2.EventBundle event_bundle = 1
     */
    eventBundle?: EventBundle;
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventHint event_hints = 2
     */
    eventHints: EventHint[];
}
/**
 * @generated from protobuf message polycentric.v2.GetPostThreadRequest
 */
export interface GetPostThreadRequest {
    /**
     * Parent post to return the thread for
     *
     * @generated from protobuf field: polycentric.v2.EventKey event_key = 1
     */
    eventKey?: EventKey;
    /**
     * @generated from protobuf field: int32 limit = 2
     */
    limit: number;
    /**
     * Label values for which the requester does not want to see content
     *
     * @generated from protobuf field: repeated string omit_labels = 3
     */
    omitLabels: string[];
}
/**
 * @generated from protobuf message polycentric.v2.GetAttributionFeedRequest
 */
export interface GetAttributionFeedRequest {
    /**
     * Attribution to match posts against. A post is included when any of
     * its `attributed_to` entries is similar to this one — for a link,
     * similar means the same URL, ignoring other Link metadata.
     *
     * @generated from protobuf field: polycentric.v2.AttributedTo attributed_to = 1
     */
    attributedTo?: AttributedTo;
    /**
     * @generated from protobuf field: optional polycentric.v2.PageParams page_params = 2
     */
    pageParams?: PageParams;
    /**
     * Label values for which the requester does not want to see content
     *
     * @generated from protobuf field: repeated string omit_labels = 3
     */
    omitLabels: string[];
}
/**
 * @generated from protobuf enum polycentric.v2.FeedAlgorithm
 */
export enum FeedAlgorithm {
    /**
     * @generated from protobuf enum value: FEED_ALGORITHM_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: FEED_ALGORITHM_FOLLOWING = 1;
     */
    FOLLOWING = 1,
    /**
     * @generated from protobuf enum value: FEED_ALGORITHM_SUGGESTED = 2;
     */
    SUGGESTED = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class GetIdentityFeedRequest$Type extends MessageType<GetIdentityFeedRequest> {
    constructor() {
        super("polycentric.v2.GetIdentityFeedRequest", [
            { no: 1, name: "identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "page_params", kind: "message", T: () => PageParams },
            { no: 3, name: "omit_labels", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetIdentityFeedRequest>): GetIdentityFeedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.identity = "";
        message.omitLabels = [];
        if (value !== undefined)
            reflectionMergePartial<GetIdentityFeedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetIdentityFeedRequest): GetIdentityFeedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string identity */ 1:
                    message.identity = reader.string();
                    break;
                case /* optional polycentric.v2.PageParams page_params */ 2:
                    message.pageParams = PageParams.internalBinaryRead(reader, reader.uint32(), options, message.pageParams);
                    break;
                case /* repeated string omit_labels */ 3:
                    message.omitLabels.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetIdentityFeedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string identity = 1; */
        if (message.identity !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.identity);
        /* optional polycentric.v2.PageParams page_params = 2; */
        if (message.pageParams)
            PageParams.internalBinaryWrite(message.pageParams, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated string omit_labels = 3; */
        for (let i = 0; i < message.omitLabels.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.omitLabels[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetIdentityFeedRequest
 */
export const GetIdentityFeedRequest = new GetIdentityFeedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetFollowingFeedRequest$Type extends MessageType<GetFollowingFeedRequest> {
    constructor() {
        super("polycentric.v2.GetFollowingFeedRequest", [
            { no: 1, name: "follower_identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "page_params", kind: "message", T: () => PageParams },
            { no: 3, name: "omit_labels", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "sort_by", kind: "enum", opt: true, T: () => ["polycentric.v2.SortPostsBy", SortPostsBy, "SORT_POSTS_BY_"] }
        ]);
    }
    create(value?: PartialMessage<GetFollowingFeedRequest>): GetFollowingFeedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.followerIdentity = "";
        message.omitLabels = [];
        if (value !== undefined)
            reflectionMergePartial<GetFollowingFeedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetFollowingFeedRequest): GetFollowingFeedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string follower_identity */ 1:
                    message.followerIdentity = reader.string();
                    break;
                case /* optional polycentric.v2.PageParams page_params */ 2:
                    message.pageParams = PageParams.internalBinaryRead(reader, reader.uint32(), options, message.pageParams);
                    break;
                case /* repeated string omit_labels */ 3:
                    message.omitLabels.push(reader.string());
                    break;
                case /* optional polycentric.v2.SortPostsBy sort_by */ 4:
                    message.sortBy = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetFollowingFeedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string follower_identity = 1; */
        if (message.followerIdentity !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.followerIdentity);
        /* optional polycentric.v2.PageParams page_params = 2; */
        if (message.pageParams)
            PageParams.internalBinaryWrite(message.pageParams, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated string omit_labels = 3; */
        for (let i = 0; i < message.omitLabels.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.omitLabels[i]);
        /* optional polycentric.v2.SortPostsBy sort_by = 4; */
        if (message.sortBy !== undefined)
            writer.tag(4, WireType.Varint).int32(message.sortBy);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetFollowingFeedRequest
 */
export const GetFollowingFeedRequest = new GetFollowingFeedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetExploreFeedRequest$Type extends MessageType<GetExploreFeedRequest> {
    constructor() {
        super("polycentric.v2.GetExploreFeedRequest", [
            { no: 1, name: "identity", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "page_params", kind: "message", T: () => PageParams },
            { no: 3, name: "omit_labels", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "sort_by", kind: "enum", opt: true, T: () => ["polycentric.v2.SortPostsBy", SortPostsBy, "SORT_POSTS_BY_"] }
        ]);
    }
    create(value?: PartialMessage<GetExploreFeedRequest>): GetExploreFeedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.omitLabels = [];
        if (value !== undefined)
            reflectionMergePartial<GetExploreFeedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetExploreFeedRequest): GetExploreFeedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string identity */ 1:
                    message.identity = reader.string();
                    break;
                case /* optional polycentric.v2.PageParams page_params */ 2:
                    message.pageParams = PageParams.internalBinaryRead(reader, reader.uint32(), options, message.pageParams);
                    break;
                case /* repeated string omit_labels */ 3:
                    message.omitLabels.push(reader.string());
                    break;
                case /* optional polycentric.v2.SortPostsBy sort_by */ 4:
                    message.sortBy = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetExploreFeedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string identity = 1; */
        if (message.identity !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.identity);
        /* optional polycentric.v2.PageParams page_params = 2; */
        if (message.pageParams)
            PageParams.internalBinaryWrite(message.pageParams, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated string omit_labels = 3; */
        for (let i = 0; i < message.omitLabels.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.omitLabels[i]);
        /* optional polycentric.v2.SortPostsBy sort_by = 4; */
        if (message.sortBy !== undefined)
            writer.tag(4, WireType.Varint).int32(message.sortBy);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetExploreFeedRequest
 */
export const GetExploreFeedRequest = new GetExploreFeedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetFeedResponse$Type extends MessageType<GetFeedResponse> {
    constructor() {
        super("polycentric.v2.GetFeedResponse", [
            { no: 1, name: "event_bundles", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventBundle },
            { no: 2, name: "event_hints", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventHint },
            { no: 3, name: "page_info", kind: "message", T: () => PageInfo }
        ]);
    }
    create(value?: PartialMessage<GetFeedResponse>): GetFeedResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventBundles = [];
        message.eventHints = [];
        if (value !== undefined)
            reflectionMergePartial<GetFeedResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetFeedResponse): GetFeedResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.EventBundle event_bundles */ 1:
                    message.eventBundles.push(EventBundle.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated polycentric.v2.EventHint event_hints */ 2:
                    message.eventHints.push(EventHint.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional polycentric.v2.PageInfo page_info */ 3:
                    message.pageInfo = PageInfo.internalBinaryRead(reader, reader.uint32(), options, message.pageInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetFeedResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.EventBundle event_bundles = 1; */
        for (let i = 0; i < message.eventBundles.length; i++)
            EventBundle.internalBinaryWrite(message.eventBundles[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.EventHint event_hints = 2; */
        for (let i = 0; i < message.eventHints.length; i++)
            EventHint.internalBinaryWrite(message.eventHints[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional polycentric.v2.PageInfo page_info = 3; */
        if (message.pageInfo)
            PageInfo.internalBinaryWrite(message.pageInfo, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetFeedResponse
 */
export const GetFeedResponse = new GetFeedResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPostThreadResponse$Type extends MessageType<GetPostThreadResponse> {
    constructor() {
        super("polycentric.v2.GetPostThreadResponse", [
            { no: 1, name: "thread", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventBundle },
            { no: 2, name: "event_hints", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventHint }
        ]);
    }
    create(value?: PartialMessage<GetPostThreadResponse>): GetPostThreadResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.thread = [];
        message.eventHints = [];
        if (value !== undefined)
            reflectionMergePartial<GetPostThreadResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPostThreadResponse): GetPostThreadResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.EventBundle thread */ 1:
                    message.thread.push(EventBundle.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated polycentric.v2.EventHint event_hints */ 2:
                    message.eventHints.push(EventHint.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPostThreadResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.EventBundle thread = 1; */
        for (let i = 0; i < message.thread.length; i++)
            EventBundle.internalBinaryWrite(message.thread[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.EventHint event_hints = 2; */
        for (let i = 0; i < message.eventHints.length; i++)
            EventHint.internalBinaryWrite(message.eventHints[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetPostThreadResponse
 */
export const GetPostThreadResponse = new GetPostThreadResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPostRequest$Type extends MessageType<GetPostRequest> {
    constructor() {
        super("polycentric.v2.GetPostRequest", [
            { no: 1, name: "event_key", kind: "message", T: () => EventKey }
        ]);
    }
    create(value?: PartialMessage<GetPostRequest>): GetPostRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetPostRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPostRequest): GetPostRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventKey event_key */ 1:
                    message.eventKey = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.eventKey);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPostRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventKey event_key = 1; */
        if (message.eventKey)
            EventKey.internalBinaryWrite(message.eventKey, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetPostRequest
 */
export const GetPostRequest = new GetPostRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPostResponse$Type extends MessageType<GetPostResponse> {
    constructor() {
        super("polycentric.v2.GetPostResponse", [
            { no: 1, name: "event_bundle", kind: "message", T: () => EventBundle },
            { no: 2, name: "event_hints", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventHint }
        ]);
    }
    create(value?: PartialMessage<GetPostResponse>): GetPostResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventHints = [];
        if (value !== undefined)
            reflectionMergePartial<GetPostResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPostResponse): GetPostResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional polycentric.v2.EventBundle event_bundle */ 1:
                    message.eventBundle = EventBundle.internalBinaryRead(reader, reader.uint32(), options, message.eventBundle);
                    break;
                case /* repeated polycentric.v2.EventHint event_hints */ 2:
                    message.eventHints.push(EventHint.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPostResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional polycentric.v2.EventBundle event_bundle = 1; */
        if (message.eventBundle)
            EventBundle.internalBinaryWrite(message.eventBundle, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.EventHint event_hints = 2; */
        for (let i = 0; i < message.eventHints.length; i++)
            EventHint.internalBinaryWrite(message.eventHints[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetPostResponse
 */
export const GetPostResponse = new GetPostResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPostThreadRequest$Type extends MessageType<GetPostThreadRequest> {
    constructor() {
        super("polycentric.v2.GetPostThreadRequest", [
            { no: 1, name: "event_key", kind: "message", T: () => EventKey },
            { no: 2, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "omit_labels", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetPostThreadRequest>): GetPostThreadRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.limit = 0;
        message.omitLabels = [];
        if (value !== undefined)
            reflectionMergePartial<GetPostThreadRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPostThreadRequest): GetPostThreadRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventKey event_key */ 1:
                    message.eventKey = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.eventKey);
                    break;
                case /* int32 limit */ 2:
                    message.limit = reader.int32();
                    break;
                case /* repeated string omit_labels */ 3:
                    message.omitLabels.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPostThreadRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventKey event_key = 1; */
        if (message.eventKey)
            EventKey.internalBinaryWrite(message.eventKey, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 limit = 2; */
        if (message.limit !== 0)
            writer.tag(2, WireType.Varint).int32(message.limit);
        /* repeated string omit_labels = 3; */
        for (let i = 0; i < message.omitLabels.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.omitLabels[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetPostThreadRequest
 */
export const GetPostThreadRequest = new GetPostThreadRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAttributionFeedRequest$Type extends MessageType<GetAttributionFeedRequest> {
    constructor() {
        super("polycentric.v2.GetAttributionFeedRequest", [
            { no: 1, name: "attributed_to", kind: "message", T: () => AttributedTo },
            { no: 2, name: "page_params", kind: "message", T: () => PageParams },
            { no: 3, name: "omit_labels", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetAttributionFeedRequest>): GetAttributionFeedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.omitLabels = [];
        if (value !== undefined)
            reflectionMergePartial<GetAttributionFeedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAttributionFeedRequest): GetAttributionFeedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.AttributedTo attributed_to */ 1:
                    message.attributedTo = AttributedTo.internalBinaryRead(reader, reader.uint32(), options, message.attributedTo);
                    break;
                case /* optional polycentric.v2.PageParams page_params */ 2:
                    message.pageParams = PageParams.internalBinaryRead(reader, reader.uint32(), options, message.pageParams);
                    break;
                case /* repeated string omit_labels */ 3:
                    message.omitLabels.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAttributionFeedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.AttributedTo attributed_to = 1; */
        if (message.attributedTo)
            AttributedTo.internalBinaryWrite(message.attributedTo, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional polycentric.v2.PageParams page_params = 2; */
        if (message.pageParams)
            PageParams.internalBinaryWrite(message.pageParams, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated string omit_labels = 3; */
        for (let i = 0; i < message.omitLabels.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.omitLabels[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetAttributionFeedRequest
 */
export const GetAttributionFeedRequest = new GetAttributionFeedRequest$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.FeedsService
 */
export const FeedsService = new ServiceType("polycentric.v2.FeedsService", [
    { name: "GetIdentityFeed", options: {}, I: GetIdentityFeedRequest, O: GetFeedResponse },
    { name: "GetFollowingFeed", options: {}, I: GetFollowingFeedRequest, O: GetFeedResponse },
    { name: "GetRecommendedFeed", options: {}, I: GetFollowingFeedRequest, O: GetFeedResponse },
    { name: "GetExploreFeed", options: {}, I: GetExploreFeedRequest, O: GetFeedResponse },
    { name: "GetPost", options: {}, I: GetPostRequest, O: GetPostResponse },
    { name: "GetPostThread", options: {}, I: GetPostThreadRequest, O: GetPostThreadResponse },
    { name: "GetAttributionFeed", options: {}, I: GetAttributionFeedRequest, O: GetFeedResponse }
]);
