// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/feeds.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { FeedsService } from "./feeds";
import type { GetAttributionFeedRequest } from "./feeds";
import type { GetPostThreadResponse } from "./feeds";
import type { GetPostThreadRequest } from "./feeds";
import type { GetPostResponse } from "./feeds";
import type { GetPostRequest } from "./feeds";
import type { GetExploreFeedRequest } from "./feeds";
import type { GetFollowingFeedRequest } from "./feeds";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetFeedResponse } from "./feeds";
import type { GetIdentityFeedRequest } from "./feeds";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * *
 * Curated feeds provided by servers
 *
 * @generated from protobuf service polycentric.v2.FeedsService
 */
export interface IFeedsServiceClient {
    /**
     * Posts that belong to an identity
     *
     * @generated from protobuf rpc: GetIdentityFeed
     */
    getIdentityFeed(input: GetIdentityFeedRequest, options?: RpcOptions): UnaryCall<GetIdentityFeedRequest, GetFeedResponse>;
    /**
     * Get posts created by the identity themselves and all identities they
     * follow.
     *
     * @generated from protobuf rpc: GetFollowingFeed
     */
    getFollowingFeed(input: GetFollowingFeedRequest, options?: RpcOptions): UnaryCall<GetFollowingFeedRequest, GetFeedResponse>;
    /**
     * Get posts created by, reacted to, reposted by, quoted or replied to by the
     * identity themselves and all identities they follow.
     *
     * @generated from protobuf rpc: GetRecommendedFeed
     */
    getRecommendedFeed(input: GetFollowingFeedRequest, options?: RpcOptions): UnaryCall<GetFollowingFeedRequest, GetFeedResponse>;
    /**
     * Get posts by any identity.
     *
     * @generated from protobuf rpc: GetExploreFeed
     */
    getExploreFeed(input: GetExploreFeedRequest, options?: RpcOptions): UnaryCall<GetExploreFeedRequest, GetFeedResponse>;
    /**
     * Get a single post.
     *
     * @generated from protobuf rpc: GetPost
     */
    getPost(input: GetPostRequest, options?: RpcOptions): UnaryCall<GetPostRequest, GetPostResponse>;
    /**
     * Replies to a post.
     *
     * @generated from protobuf rpc: GetPostThread
     */
    getPostThread(input: GetPostThreadRequest, options?: RpcOptions): UnaryCall<GetPostThreadRequest, GetPostThreadResponse>;
    /**
     * Posts attributed to the same target (e.g. all posts about a URL)
     *
     * @generated from protobuf rpc: GetAttributionFeed
     */
    getAttributionFeed(input: GetAttributionFeedRequest, options?: RpcOptions): UnaryCall<GetAttributionFeedRequest, GetFeedResponse>;
}
/**
 * *
 * Curated feeds provided by servers
 *
 * @generated from protobuf service polycentric.v2.FeedsService
 */
export class FeedsServiceClient implements IFeedsServiceClient, ServiceInfo {
    typeName = FeedsService.typeName;
    methods = FeedsService.methods;
    options = FeedsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Posts that belong to an identity
     *
     * @generated from protobuf rpc: GetIdentityFeed
     */
    getIdentityFeed(input: GetIdentityFeedRequest, options?: RpcOptions): UnaryCall<GetIdentityFeedRequest, GetFeedResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetIdentityFeedRequest, GetFeedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get posts created by the identity themselves and all identities they
     * follow.
     *
     * @generated from protobuf rpc: GetFollowingFeed
     */
    getFollowingFeed(input: GetFollowingFeedRequest, options?: RpcOptions): UnaryCall<GetFollowingFeedRequest, GetFeedResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetFollowingFeedRequest, GetFeedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get posts created by, reacted to, reposted by, quoted or replied to by the
     * identity themselves and all identities they follow.
     *
     * @generated from protobuf rpc: GetRecommendedFeed
     */
    getRecommendedFeed(input: GetFollowingFeedRequest, options?: RpcOptions): UnaryCall<GetFollowingFeedRequest, GetFeedResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetFollowingFeedRequest, GetFeedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get posts by any identity.
     *
     * @generated from protobuf rpc: GetExploreFeed
     */
    getExploreFeed(input: GetExploreFeedRequest, options?: RpcOptions): UnaryCall<GetExploreFeedRequest, GetFeedResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetExploreFeedRequest, GetFeedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get a single post.
     *
     * @generated from protobuf rpc: GetPost
     */
    getPost(input: GetPostRequest, options?: RpcOptions): UnaryCall<GetPostRequest, GetPostResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPostRequest, GetPostResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Replies to a post.
     *
     * @generated from protobuf rpc: GetPostThread
     */
    getPostThread(input: GetPostThreadRequest, options?: RpcOptions): UnaryCall<GetPostThreadRequest, GetPostThreadResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPostThreadRequest, GetPostThreadResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Posts attributed to the same target (e.g. all posts about a URL)
     *
     * @generated from protobuf rpc: GetAttributionFeed
     */
    getAttributionFeed(input: GetAttributionFeedRequest, options?: RpcOptions): UnaryCall<GetAttributionFeedRequest, GetFeedResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAttributionFeedRequest, GetFeedResponse>("unary", this._transport, method, opt, input);
    }
}
