// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/pairing_service.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { EventBundle } from "./events";
import { PublicKey } from "./keypair";
/**
 * Immutable state created at the start of a pairing session that uniquely
 * identifies it.
 *
 * @generated from protobuf message polycentric.v2.PairingSessionDigest
 */
export interface PairingSessionDigest {
    /**
     * Trusted source of truth for the identity being paired with.
     *
     * @generated from protobuf field: string issuer_identity = 1
     */
    issuerIdentity: string;
    /**
     * Each issuer state must be signed by this key and this key must be
     * authorized for rotation.
     *
     * @generated from protobuf field: polycentric.v2.PublicKey issuer_signer = 2
     */
    issuerSigner?: PublicKey;
    /**
     * Random bitstring to add entropy and keep session identifiers unpredictable.
     *
     * @generated from protobuf field: bytes nonce = 3
     */
    nonce: Uint8Array;
    /**
     * Timestamp in posix epoch millis.
     * Used for expiration and preventing replay attacks.
     *
     * @generated from protobuf field: int64 initial_timestamp = 4
     */
    initialTimestamp: bigint;
    /**
     * The number of milliseconds after the initial timestamp for which this
     * session is considered valid.
     *
     * @generated from protobuf field: int64 ttl_millis = 5
     */
    ttlMillis: bigint;
}
/**
 * Data to share out-of-band between the issuer and claimer.
 * This means using copy/paste or a QR code.
 *
 * @generated from protobuf message polycentric.v2.PairingInfo
 */
export interface PairingInfo {
    /**
     * URL of the server that holds this pairing session.
     *
     * @generated from protobuf field: string server = 1
     */
    server: string;
    /**
     * SHA256 hash of the pairing session digest.
     *
     * @generated from protobuf field: bytes digest_sha256 = 2
     */
    digestSha256: Uint8Array;
}
/**
 * Signed payload from issuers that contains pairing state information.
 * Contains authenticated information about the pairing session for claimers and
 * servers to read.
 * Clients and servers should only obtain messages of this type from a
 * `SignedIssuerState` message and must check its signature.
 *
 * @generated from protobuf message polycentric.v2.IssuerPairingState
 */
export interface IssuerPairingState {
    /**
     * Serialized `PairingSessionDigest` message.
     * Identifies the pairing session that this state belongs to.
     * This should be kept constant throughout the session.
     * Clients should verify that the SHA256 hash and content of this field
     * matches what they expect.
     *
     * @generated from protobuf field: bytes session_digest = 1
     */
    sessionDigest: Uint8Array;
    /**
     * The most recent identity event for this identity as reported by the issuer.
     * Claimers should verify the full identity chain before fully trusting the
     * content of this field.
     * Even when not fully trusted, it is still useful for:
     * - seeding the list of servers to query.
     * - deciding when to try claiming.
     *
     * @generated from protobuf field: polycentric.v2.EventBundle identity_state = 2
     */
    identityState?: EventBundle;
    /**
     * A counter that gets incremented for each new state in this pairing session.
     * This keeps updates well-ordered and prevents replay attacks from rolling
     * back state.
     * Starts at 1 for each pairing session.
     *
     * @generated from protobuf field: int64 sequence = 3
     */
    sequence: bigint;
}
/**
 * Encapsulates an issuer's signed pairing state and its signature.
 *
 * @generated from protobuf message polycentric.v2.SignedIssuerState
 */
export interface SignedIssuerState {
    /**
     * Serialized `IssuerPairingState` message from the issuer.
     *
     * @generated from protobuf field: bytes state_bytes = 1
     */
    stateBytes: Uint8Array;
    /**
     * Signature over `state_bytes`.
     * Must use the key pair specified in the digest.
     *
     * @generated from protobuf field: bytes signature = 2
     */
    signature: Uint8Array;
}
/**
 * Server-aggregated state for a pairing session containing input from the
 * issuer and claimers.
 *
 * @generated from protobuf message polycentric.v2.PairingSessionState
 */
export interface PairingSessionState {
    /**
     * @generated from protobuf field: polycentric.v2.SignedIssuerState issuer_state = 1
     */
    issuerState?: SignedIssuerState;
    /**
     * Server-managed list of claimers.
     *
     * @generated from protobuf field: repeated polycentric.v2.PublicKey claimers = 2
     */
    claimers: PublicKey[];
}
/**
 * *
 * Request payload for fetching a pairing session.
 *
 * @generated from protobuf message polycentric.v2.GetPairingSessionRequest
 */
export interface GetPairingSessionRequest {
    /**
     * @generated from protobuf field: bytes digest_sha256 = 1
     */
    digestSha256: Uint8Array;
}
/**
 * *
 * Wrapper request for PutPairingSession RPC.
 *
 * @generated from protobuf message polycentric.v2.PutPairingSessionRequest
 */
export interface PutPairingSessionRequest {
    /**
     * @generated from protobuf field: polycentric.v2.SignedIssuerState issuer_state = 1
     */
    issuerState?: SignedIssuerState;
}
/**
 * *
 * Wrapper response for PutPairingSession RPC.
 *
 * @generated from protobuf message polycentric.v2.PutPairingSessionResponse
 */
export interface PutPairingSessionResponse {
    /**
     * @generated from protobuf field: polycentric.v2.PairingSessionState session_state = 1
     */
    sessionState?: PairingSessionState;
}
/**
 * *
 * Wrapper response for GetPairingSession RPC.
 *
 * @generated from protobuf message polycentric.v2.GetPairingSessionResponse
 */
export interface GetPairingSessionResponse {
    /**
     * @generated from protobuf field: polycentric.v2.PairingSessionState session_state = 1
     */
    sessionState?: PairingSessionState;
}
/**
 * *
 * Wrapper request for JoinPairingSession RPC.
 *
 * @generated from protobuf message polycentric.v2.JoinPairingSessionRequest
 */
export interface JoinPairingSessionRequest {
    /**
     * SHA256 of the pairing session digest to join.
     *
     * @generated from protobuf field: bytes digest_sha256 = 1
     */
    digestSha256: Uint8Array;
    /**
     * Public key that the claimer wishes to join with.
     *
     * @generated from protobuf field: polycentric.v2.PublicKey claimer_key = 2
     */
    claimerKey?: PublicKey;
}
/**
 * *
 * Wrapper response for JoinPairingSession RPC.
 *
 * @generated from protobuf message polycentric.v2.JoinPairingSessionResponse
 */
export interface JoinPairingSessionResponse {
    /**
     * @generated from protobuf field: polycentric.v2.PairingSessionState session_state = 1
     */
    sessionState?: PairingSessionState;
}
// @generated message type with reflection information, may provide speed optimized methods
class PairingSessionDigest$Type extends MessageType<PairingSessionDigest> {
    constructor() {
        super("polycentric.v2.PairingSessionDigest", [
            { no: 1, name: "issuer_identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "issuer_signer", kind: "message", T: () => PublicKey },
            { no: 3, name: "nonce", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 4, name: "initial_timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "ttl_millis", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<PairingSessionDigest>): PairingSessionDigest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.issuerIdentity = "";
        message.nonce = new Uint8Array(0);
        message.initialTimestamp = 0n;
        message.ttlMillis = 0n;
        if (value !== undefined)
            reflectionMergePartial<PairingSessionDigest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PairingSessionDigest): PairingSessionDigest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string issuer_identity */ 1:
                    message.issuerIdentity = reader.string();
                    break;
                case /* polycentric.v2.PublicKey issuer_signer */ 2:
                    message.issuerSigner = PublicKey.internalBinaryRead(reader, reader.uint32(), options, message.issuerSigner);
                    break;
                case /* bytes nonce */ 3:
                    message.nonce = reader.bytes();
                    break;
                case /* int64 initial_timestamp */ 4:
                    message.initialTimestamp = reader.int64().toBigInt();
                    break;
                case /* int64 ttl_millis */ 5:
                    message.ttlMillis = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PairingSessionDigest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string issuer_identity = 1; */
        if (message.issuerIdentity !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.issuerIdentity);
        /* polycentric.v2.PublicKey issuer_signer = 2; */
        if (message.issuerSigner)
            PublicKey.internalBinaryWrite(message.issuerSigner, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* bytes nonce = 3; */
        if (message.nonce.length)
            writer.tag(3, WireType.LengthDelimited).bytes(message.nonce);
        /* int64 initial_timestamp = 4; */
        if (message.initialTimestamp !== 0n)
            writer.tag(4, WireType.Varint).int64(message.initialTimestamp);
        /* int64 ttl_millis = 5; */
        if (message.ttlMillis !== 0n)
            writer.tag(5, WireType.Varint).int64(message.ttlMillis);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PairingSessionDigest
 */
export const PairingSessionDigest = new PairingSessionDigest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PairingInfo$Type extends MessageType<PairingInfo> {
    constructor() {
        super("polycentric.v2.PairingInfo", [
            { no: 1, name: "server", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "digest_sha256", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<PairingInfo>): PairingInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.server = "";
        message.digestSha256 = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<PairingInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PairingInfo): PairingInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string server */ 1:
                    message.server = reader.string();
                    break;
                case /* bytes digest_sha256 */ 2:
                    message.digestSha256 = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PairingInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string server = 1; */
        if (message.server !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.server);
        /* bytes digest_sha256 = 2; */
        if (message.digestSha256.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.digestSha256);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PairingInfo
 */
export const PairingInfo = new PairingInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IssuerPairingState$Type extends MessageType<IssuerPairingState> {
    constructor() {
        super("polycentric.v2.IssuerPairingState", [
            { no: 1, name: "session_digest", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "identity_state", kind: "message", T: () => EventBundle },
            { no: 3, name: "sequence", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<IssuerPairingState>): IssuerPairingState {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sessionDigest = new Uint8Array(0);
        message.sequence = 0n;
        if (value !== undefined)
            reflectionMergePartial<IssuerPairingState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IssuerPairingState): IssuerPairingState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes session_digest */ 1:
                    message.sessionDigest = reader.bytes();
                    break;
                case /* polycentric.v2.EventBundle identity_state */ 2:
                    message.identityState = EventBundle.internalBinaryRead(reader, reader.uint32(), options, message.identityState);
                    break;
                case /* int64 sequence */ 3:
                    message.sequence = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IssuerPairingState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes session_digest = 1; */
        if (message.sessionDigest.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.sessionDigest);
        /* polycentric.v2.EventBundle identity_state = 2; */
        if (message.identityState)
            EventBundle.internalBinaryWrite(message.identityState, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* int64 sequence = 3; */
        if (message.sequence !== 0n)
            writer.tag(3, WireType.Varint).int64(message.sequence);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.IssuerPairingState
 */
export const IssuerPairingState = new IssuerPairingState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SignedIssuerState$Type extends MessageType<SignedIssuerState> {
    constructor() {
        super("polycentric.v2.SignedIssuerState", [
            { no: 1, name: "state_bytes", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<SignedIssuerState>): SignedIssuerState {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.stateBytes = new Uint8Array(0);
        message.signature = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<SignedIssuerState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SignedIssuerState): SignedIssuerState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes state_bytes */ 1:
                    message.stateBytes = reader.bytes();
                    break;
                case /* bytes signature */ 2:
                    message.signature = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SignedIssuerState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes state_bytes = 1; */
        if (message.stateBytes.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.stateBytes);
        /* bytes signature = 2; */
        if (message.signature.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.signature);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SignedIssuerState
 */
export const SignedIssuerState = new SignedIssuerState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PairingSessionState$Type extends MessageType<PairingSessionState> {
    constructor() {
        super("polycentric.v2.PairingSessionState", [
            { no: 1, name: "issuer_state", kind: "message", T: () => SignedIssuerState },
            { no: 2, name: "claimers", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PublicKey }
        ]);
    }
    create(value?: PartialMessage<PairingSessionState>): PairingSessionState {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.claimers = [];
        if (value !== undefined)
            reflectionMergePartial<PairingSessionState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PairingSessionState): PairingSessionState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.SignedIssuerState issuer_state */ 1:
                    message.issuerState = SignedIssuerState.internalBinaryRead(reader, reader.uint32(), options, message.issuerState);
                    break;
                case /* repeated polycentric.v2.PublicKey claimers */ 2:
                    message.claimers.push(PublicKey.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PairingSessionState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.SignedIssuerState issuer_state = 1; */
        if (message.issuerState)
            SignedIssuerState.internalBinaryWrite(message.issuerState, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.PublicKey claimers = 2; */
        for (let i = 0; i < message.claimers.length; i++)
            PublicKey.internalBinaryWrite(message.claimers[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PairingSessionState
 */
export const PairingSessionState = new PairingSessionState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPairingSessionRequest$Type extends MessageType<GetPairingSessionRequest> {
    constructor() {
        super("polycentric.v2.GetPairingSessionRequest", [
            { no: 1, name: "digest_sha256", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<GetPairingSessionRequest>): GetPairingSessionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.digestSha256 = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<GetPairingSessionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPairingSessionRequest): GetPairingSessionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes digest_sha256 */ 1:
                    message.digestSha256 = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPairingSessionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes digest_sha256 = 1; */
        if (message.digestSha256.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.digestSha256);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetPairingSessionRequest
 */
export const GetPairingSessionRequest = new GetPairingSessionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PutPairingSessionRequest$Type extends MessageType<PutPairingSessionRequest> {
    constructor() {
        super("polycentric.v2.PutPairingSessionRequest", [
            { no: 1, name: "issuer_state", kind: "message", T: () => SignedIssuerState }
        ]);
    }
    create(value?: PartialMessage<PutPairingSessionRequest>): PutPairingSessionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<PutPairingSessionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PutPairingSessionRequest): PutPairingSessionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.SignedIssuerState issuer_state */ 1:
                    message.issuerState = SignedIssuerState.internalBinaryRead(reader, reader.uint32(), options, message.issuerState);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PutPairingSessionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.SignedIssuerState issuer_state = 1; */
        if (message.issuerState)
            SignedIssuerState.internalBinaryWrite(message.issuerState, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PutPairingSessionRequest
 */
export const PutPairingSessionRequest = new PutPairingSessionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PutPairingSessionResponse$Type extends MessageType<PutPairingSessionResponse> {
    constructor() {
        super("polycentric.v2.PutPairingSessionResponse", [
            { no: 1, name: "session_state", kind: "message", T: () => PairingSessionState }
        ]);
    }
    create(value?: PartialMessage<PutPairingSessionResponse>): PutPairingSessionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<PutPairingSessionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PutPairingSessionResponse): PutPairingSessionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.PairingSessionState session_state */ 1:
                    message.sessionState = PairingSessionState.internalBinaryRead(reader, reader.uint32(), options, message.sessionState);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PutPairingSessionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.PairingSessionState session_state = 1; */
        if (message.sessionState)
            PairingSessionState.internalBinaryWrite(message.sessionState, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PutPairingSessionResponse
 */
export const PutPairingSessionResponse = new PutPairingSessionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPairingSessionResponse$Type extends MessageType<GetPairingSessionResponse> {
    constructor() {
        super("polycentric.v2.GetPairingSessionResponse", [
            { no: 1, name: "session_state", kind: "message", T: () => PairingSessionState }
        ]);
    }
    create(value?: PartialMessage<GetPairingSessionResponse>): GetPairingSessionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetPairingSessionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPairingSessionResponse): GetPairingSessionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.PairingSessionState session_state */ 1:
                    message.sessionState = PairingSessionState.internalBinaryRead(reader, reader.uint32(), options, message.sessionState);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPairingSessionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.PairingSessionState session_state = 1; */
        if (message.sessionState)
            PairingSessionState.internalBinaryWrite(message.sessionState, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetPairingSessionResponse
 */
export const GetPairingSessionResponse = new GetPairingSessionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JoinPairingSessionRequest$Type extends MessageType<JoinPairingSessionRequest> {
    constructor() {
        super("polycentric.v2.JoinPairingSessionRequest", [
            { no: 1, name: "digest_sha256", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "claimer_key", kind: "message", T: () => PublicKey }
        ]);
    }
    create(value?: PartialMessage<JoinPairingSessionRequest>): JoinPairingSessionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.digestSha256 = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<JoinPairingSessionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinPairingSessionRequest): JoinPairingSessionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes digest_sha256 */ 1:
                    message.digestSha256 = reader.bytes();
                    break;
                case /* polycentric.v2.PublicKey claimer_key */ 2:
                    message.claimerKey = PublicKey.internalBinaryRead(reader, reader.uint32(), options, message.claimerKey);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JoinPairingSessionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes digest_sha256 = 1; */
        if (message.digestSha256.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.digestSha256);
        /* polycentric.v2.PublicKey claimer_key = 2; */
        if (message.claimerKey)
            PublicKey.internalBinaryWrite(message.claimerKey, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.JoinPairingSessionRequest
 */
export const JoinPairingSessionRequest = new JoinPairingSessionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JoinPairingSessionResponse$Type extends MessageType<JoinPairingSessionResponse> {
    constructor() {
        super("polycentric.v2.JoinPairingSessionResponse", [
            { no: 1, name: "session_state", kind: "message", T: () => PairingSessionState }
        ]);
    }
    create(value?: PartialMessage<JoinPairingSessionResponse>): JoinPairingSessionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<JoinPairingSessionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinPairingSessionResponse): JoinPairingSessionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.PairingSessionState session_state */ 1:
                    message.sessionState = PairingSessionState.internalBinaryRead(reader, reader.uint32(), options, message.sessionState);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JoinPairingSessionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.PairingSessionState session_state = 1; */
        if (message.sessionState)
            PairingSessionState.internalBinaryWrite(message.sessionState, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.JoinPairingSessionResponse
 */
export const JoinPairingSessionResponse = new JoinPairingSessionResponse$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.PairingService
 */
export const PairingService = new ServiceType("polycentric.v2.PairingService", [
    { name: "PutPairingSession", options: {}, I: PutPairingSessionRequest, O: PutPairingSessionResponse },
    { name: "GetPairingSession", options: {}, I: GetPairingSessionRequest, O: GetPairingSessionResponse },
    { name: "JoinPairingSession", options: {}, I: JoinPairingSessionRequest, O: JoinPairingSessionResponse }
]);
