[package]
name = "common-object-store"
version = "0.0.1"
edition = "2024"

[dependencies]
polycentric-common.workspace = true
aws-config = { version = "1", default-features = false, features = ["behavior-version-latest", "rt-tokio", "default-https-client"] }
aws-sdk-s3 = { version = "1", default-features = false, features = ["behavior-version-latest", "rt-tokio", "default-https-client"] }
