[package]
name = "server"
version = "0.0.1"
edition = "2024"
default-run = "server"

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "decode_response"
path = "src/bin/decode_response.rs"

[dependencies]
# Workspace
common-dotenv = { path = "../common/dotenv" }
common-kafka = { path = "../common/kafka" }
common-object-store = { path = "../common/object-store" }
common-telemetry = { path = "../common/telemetry" }
entity = { path = "./entity" }

# 3rd Party
axum = { version = "0.8.8", default-features = false, features = ["http2"] }
base64.workspace = true
chrono.workspace = true
hex.workspace = true
polycentric-common.workspace = true
prost.workspace = true
prost-types.workspace = true
rdkafka.workspace = true
reqwest = { version = "0.13", default-features = false, features = ["rustls", "json", "query"] }
sea-orm = { workspace = true, features = ["sqlx-postgres", "runtime-tokio", "macros", "mock", "postgres-array"] }
serde = { version = "1", default-features = false, features = ["std", "derive"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
sha2.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util = { version = "0.7.18", features = ["rt"] }
tonic = { workspace = true, features = ["router", "transport"] }
tonic-reflection = { version = "0.14", default-features = false, features = ["server"] }
tonic-web = { version = "0.14", default-features = false }
opentelemetry.workspace = true
tracing.workspace = true
tower-http = { version = "0.7", default-features = false, features = ["cors"] }
tower-layer = { version = "0.3", default-features = false }
http = { version = "1", default-features = false, features = ["std"] }

[dev-dependencies]
ed25519-dalek.workspace = true
mockito = { version = "1", default-features = false }
tower = { version = "0.5", default-features = false }
