--
-- PostgreSQL database dump
--

\restrict pDfhDFSWlMVwKJJCtVjCu9jpArxFvkN6yDVEZFQGYIycOWdbwu1Quua6JieaPNw

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg13+2)
-- Dumped by pg_dump version 18.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: tsvector_agg(tsvector); Type: AGGREGATE; Schema: public; Owner: -
--

CREATE AGGREGATE public.tsvector_agg(tsvector) (
    SFUNC = tsvector_concat,
    STYPE = tsvector,
    INITCOND = ''
);


--
-- Name: create_tsvector(regconfig, text, "char"); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.create_tsvector(config regconfig, text text, weight "char") RETURNS tsvector
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
    RETURN (setweight((SELECT public.tsvector_agg(strip(to_tsvector('simple'::regconfig, data.word))) AS tsvector_agg FROM string_to_table(COALESCE(create_tsvector.text, ''::text), ' '::text) data(word) WHERE starts_with(data.word, '#'::text)), weight) || setweight(strip(to_tsvector(config, COALESCE(text, ''::text))), weight));


--
-- Name: reaction_count_decay(bigint, timestamp with time zone, numeric, timestamp with time zone); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.reaction_count_decay(reaction_count bigint, post_created_at timestamp with time zone, gravity numeric, gravity_time timestamp with time zone) RETURNS numeric
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
    RETURN ((((reaction_count + 1))::numeric / power((GREATEST((EXTRACT(epoch FROM (gravity_time - post_created_at)) / (3600)::numeric), (0)::numeric) + (2)::numeric), gravity)))::numeric(20,11);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: gravity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gravity (
    value numeric(20,11) NOT NULL,
    calculated_at timestamp with time zone NOT NULL
);


--
-- Name: TABLE gravity; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.gravity IS 'Table to hold the dynamic gravity value.';


--
-- Name: reaction_count_decay(bigint, timestamp with time zone); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.reaction_count_decay(reaction_count bigint, post_created_at timestamp with time zone) RETURNS numeric
    LANGUAGE sql STABLE PARALLEL SAFE
    RETURN public.reaction_count_decay(reaction_count, post_created_at, (SELECT gravity.value FROM public.gravity), (SELECT gravity.calculated_at FROM public.gravity));


--
-- Name: reaction_count_decay(bigint, timestamp with time zone, numeric); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.reaction_count_decay(reaction_count bigint, post_created_at timestamp with time zone, gravity numeric) RETURNS numeric
    LANGUAGE sql STABLE PARALLEL SAFE
    RETURN public.reaction_count_decay(reaction_count, post_created_at, gravity, (SELECT gravity.calculated_at FROM public.gravity));


--
-- Name: search_query(text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.search_query(query text) RETURNS tsquery
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
    RETURN (COALESCE(to_tsquery('english'::regconfig, query), to_tsquery('simple'::regconfig, ''::text)) || COALESCE(to_tsquery('simple'::regconfig, query), to_tsquery('simple'::regconfig, ''::text)));


--
-- Name: application; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application (
    id integer NOT NULL,
    name text NOT NULL,
    identifier text NOT NULL,
    version text NOT NULL,
    url text NOT NULL
);


--
-- Name: application_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attributed_to_reaction_summaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attributed_to_reaction_summaries (
    url character varying NOT NULL,
    upvote_count bigint NOT NULL,
    downvote_count bigint NOT NULL
);


--
-- Name: ban; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ban (
    identity character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    banned_by character varying
);


--
-- Name: block; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.block (
    event_id bigint NOT NULL,
    blocker text NOT NULL,
    blocked text NOT NULL
);


--
-- Name: content; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content (
    id bigint NOT NULL,
    digest_type integer NOT NULL,
    digest_bytes bytea NOT NULL,
    serialized_bytes bytea NOT NULL,
    synced_at timestamp with time zone NOT NULL
);


--
-- Name: content_attributed_to_reaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_attributed_to_reaction (
    content_id bigint NOT NULL,
    url character varying NOT NULL,
    emoji character varying,
    positive boolean NOT NULL
);


--
-- Name: content_blob; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_blob (
    content_id bigint NOT NULL,
    digest_type smallint NOT NULL,
    digest_bytes bytea NOT NULL,
    mime_type character varying NOT NULL,
    size bigint NOT NULL
);


--
-- Name: content_block; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_block (
    content_id bigint NOT NULL,
    identity_id character varying NOT NULL
);


--
-- Name: content_delete; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_delete (
    content_id bigint NOT NULL,
    event_key_collection smallint NOT NULL,
    event_key_identity character varying NOT NULL,
    event_key_public_key_type smallint NOT NULL,
    event_key_public_key bytea NOT NULL,
    event_key_sequence bigint NOT NULL
);


--
-- Name: content_follow; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_follow (
    content_id bigint NOT NULL,
    identity_id character varying NOT NULL
);


--
-- Name: content_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.content ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_identity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_identity (
    content_id bigint NOT NULL,
    identity character varying NOT NULL,
    identity_bytes bytea NOT NULL,
    rotation_keys jsonb DEFAULT '[]'::jsonb NOT NULL,
    signing_keys jsonb DEFAULT '[]'::jsonb NOT NULL,
    revocation_bounds jsonb DEFAULT '[]'::jsonb NOT NULL,
    servers jsonb
);


--
-- Name: content_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_image (
    content_id bigint NOT NULL,
    blob_digest_type smallint NOT NULL,
    blob_digest_bytes bytea NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL
);


--
-- Name: content_label; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_label (
    content_id bigint NOT NULL,
    label_value character varying NOT NULL,
    event_key_collection smallint NOT NULL,
    event_key_identity character varying NOT NULL,
    event_key_public_key_type smallint NOT NULL,
    event_key_public_key bytea NOT NULL,
    event_key_sequence bigint NOT NULL
);


--
-- Name: content_post; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_post (
    content_id bigint NOT NULL,
    text character varying NOT NULL,
    reply_root_collection smallint,
    reply_root_identity character varying,
    reply_root_public_key_type smallint,
    reply_root_public_key bytea,
    reply_root_sequence bigint,
    reply_parent_collection smallint,
    reply_parent_identity character varying,
    reply_parent_public_key_type smallint,
    reply_parent_public_key bytea,
    reply_parent_sequence bigint,
    quote_collection smallint,
    quote_identity character varying,
    quote_public_key_type smallint,
    quote_public_key bytea,
    quote_sequence bigint,
    search_data tsvector GENERATED ALWAYS AS (public.create_tsvector('english'::regconfig, (text)::text, 'A'::"char")) STORED NOT NULL
);


--
-- Name: content_post_attributed_url; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_post_attributed_url (
    content_id bigint NOT NULL,
    url character varying NOT NULL
);


--
-- Name: content_profile_update; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_profile_update (
    content_id bigint NOT NULL,
    name character varying,
    avatar jsonb,
    banner jsonb,
    description text,
    alias text,
    search_data tsvector GENERATED ALWAYS AS (((public.create_tsvector('simple'::regconfig, alias, 'A'::"char") || public.create_tsvector('simple'::regconfig, (name)::text, 'B'::"char")) || public.create_tsvector('english'::regconfig, description, 'C'::"char"))) STORED NOT NULL
);


--
-- Name: content_reaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_reaction (
    content_id bigint NOT NULL,
    event_key_collection smallint NOT NULL,
    event_key_identity character varying NOT NULL,
    event_key_public_key_type smallint NOT NULL,
    event_key_public_key bytea NOT NULL,
    event_key_sequence bigint NOT NULL,
    emoji character varying,
    positive boolean NOT NULL
);


--
-- Name: content_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_report (
    content_id bigint NOT NULL,
    category smallint NOT NULL,
    additional_info character varying NOT NULL,
    event_key_collection smallint NOT NULL,
    event_key_identity character varying NOT NULL,
    event_key_public_key_type smallint NOT NULL,
    event_key_public_key bytea NOT NULL,
    event_key_sequence bigint NOT NULL
);


--
-- Name: content_repost; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_repost (
    content_id bigint NOT NULL,
    event_key_collection smallint NOT NULL,
    event_key_identity character varying NOT NULL,
    event_key_public_key_type smallint NOT NULL,
    event_key_public_key bytea NOT NULL,
    event_key_sequence bigint NOT NULL
);


--
-- Name: content_verification_claim; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_verification_claim (
    content_id bigint NOT NULL,
    schema_digest_type integer NOT NULL,
    schema_digest_bytes bytea NOT NULL,
    fields jsonb NOT NULL
);


--
-- Name: content_verification_target; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_verification_target (
    content_id bigint NOT NULL,
    target_identity character varying NOT NULL,
    claim_event_key_collection smallint NOT NULL,
    claim_event_key_identity character varying NOT NULL,
    claim_event_key_public_key_type smallint CONSTRAINT content_verification_target_claim_event_key_public_key_not_null NOT NULL,
    claim_event_key_public_key bytea CONSTRAINT content_verification_targe_claim_event_key_public_key_not_null1 NOT NULL,
    claim_event_key_sequence bigint NOT NULL
);


--
-- Name: content_verification_verify; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_verification_verify (
    content_id bigint NOT NULL,
    claim_event_key_collection smallint NOT NULL,
    claim_event_key_identity character varying NOT NULL,
    claim_event_key_public_key_type smallint CONSTRAINT content_verification_verify_claim_event_key_public_key_not_null NOT NULL,
    claim_event_key_public_key bytea CONSTRAINT content_verification_verif_claim_event_key_public_key_not_null1 NOT NULL,
    claim_event_key_sequence bigint NOT NULL
);


--
-- Name: default_follow_suggestion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.default_follow_suggestion (
    identity text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id bigint NOT NULL,
    collection smallint NOT NULL,
    identity character varying NOT NULL,
    public_key_type smallint NOT NULL,
    public_key bytea NOT NULL,
    sequence bigint NOT NULL,
    content_digest_type integer,
    content_digest_bytes bytea,
    signature bytea NOT NULL,
    previous_signature bytea NOT NULL,
    previous_root bytea NOT NULL,
    event_bytes bytea NOT NULL,
    created_at timestamp with time zone NOT NULL,
    synced_at timestamp with time zone NOT NULL,
    application_id integer
);


--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: follow; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.follow (
    event_id bigint NOT NULL,
    follower text NOT NULL,
    followee text NOT NULL
);


--
-- Name: moderator; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.moderator (
    identity character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    kind integer NOT NULL,
    from_identity character varying NOT NULL,
    to_identity character varying NOT NULL,
    trigger_event_key_collection smallint NOT NULL,
    trigger_event_key_identity character varying NOT NULL,
    trigger_event_key_public_key_type smallint NOT NULL,
    trigger_event_key_public_key bytea NOT NULL,
    trigger_event_key_sequence bigint NOT NULL,
    target_event_key_collection smallint NOT NULL,
    target_event_key_identity character varying NOT NULL,
    target_event_key_public_key_type smallint NOT NULL,
    target_event_key_public_key bytea NOT NULL,
    target_event_key_sequence bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pairing_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pairing_session (
    issuer_identity character varying NOT NULL,
    digest_sha256 bytea NOT NULL,
    issuer_state_bytes bytea NOT NULL,
    issuer_state_signature bytea NOT NULL,
    initial_timestamp timestamp with time zone NOT NULL,
    sequence bigint NOT NULL
);


--
-- Name: pairing_session_claimer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pairing_session_claimer (
    digest_sha256 bytea NOT NULL,
    claimer_key_type integer NOT NULL,
    claimer_key bytea NOT NULL,
    issuer_identity character varying NOT NULL
);


--
-- Name: profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile (
    event_id bigint NOT NULL,
    identity text NOT NULL,
    name text,
    search_data tsvector NOT NULL
);


--
-- Name: quote; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quote (
    event_id bigint NOT NULL,
    identity text NOT NULL,
    post bigint NOT NULL
);


--
-- Name: reaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reaction (
    event_id bigint NOT NULL,
    on_post bigint NOT NULL,
    emoji text,
    positive boolean NOT NULL,
    identity text NOT NULL
);


--
-- Name: reaction_tally; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reaction_tally (
    event_id bigint NOT NULL,
    positive_count bigint NOT NULL,
    negative_count bigint NOT NULL,
    decayed_count numeric(20,11) NOT NULL
);


--
-- Name: reply; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reply (
    event_id bigint NOT NULL,
    identity text NOT NULL,
    post bigint NOT NULL
);


--
-- Name: repost; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.repost (
    event_id bigint NOT NULL,
    identity text NOT NULL,
    post bigint NOT NULL
);


--
-- Name: seaql_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seaql_migrations (
    version character varying NOT NULL,
    applied_at bigint NOT NULL
);


--
-- Name: url_info_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.url_info_cache (
    url character varying NOT NULL,
    title character varying NOT NULL,
    description character varying NOT NULL,
    image character varying NOT NULL,
    raw_response character varying,
    error_code integer,
    error_message character varying,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: verification_schema; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_schema (
    digest_type integer NOT NULL,
    digest_bytes bytea NOT NULL,
    schema_bytes bytea NOT NULL,
    schema jsonb NOT NULL
);


--
-- Name: application application_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT application_pkey PRIMARY KEY (id);


--
-- Name: attributed_to_reaction_summaries attributed_to_reaction_summaries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attributed_to_reaction_summaries
    ADD CONSTRAINT attributed_to_reaction_summaries_pkey PRIMARY KEY (url);


--
-- Name: ban ban_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ban
    ADD CONSTRAINT ban_pkey PRIMARY KEY (identity);


--
-- Name: block block_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.block
    ADD CONSTRAINT block_pkey PRIMARY KEY (event_id);


--
-- Name: content_attributed_to_reaction content_attributed_to_reaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_attributed_to_reaction
    ADD CONSTRAINT content_attributed_to_reaction_pkey PRIMARY KEY (content_id);


--
-- Name: content_blob content_blob_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_blob
    ADD CONSTRAINT content_blob_pkey PRIMARY KEY (content_id);


--
-- Name: content_block content_block_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_block
    ADD CONSTRAINT content_block_pkey PRIMARY KEY (content_id);


--
-- Name: content_delete content_delete_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_delete
    ADD CONSTRAINT content_delete_pkey PRIMARY KEY (content_id);


--
-- Name: content_follow content_follow_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_follow
    ADD CONSTRAINT content_follow_pkey PRIMARY KEY (content_id);


--
-- Name: content_identity content_identity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_identity
    ADD CONSTRAINT content_identity_pkey PRIMARY KEY (content_id);


--
-- Name: content_image content_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_image
    ADD CONSTRAINT content_image_pkey PRIMARY KEY (content_id);


--
-- Name: content content_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content
    ADD CONSTRAINT content_pkey PRIMARY KEY (id);


--
-- Name: content_post content_post_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_post
    ADD CONSTRAINT content_post_pkey PRIMARY KEY (content_id);


--
-- Name: content_profile_update content_profile_update_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_profile_update
    ADD CONSTRAINT content_profile_update_pkey PRIMARY KEY (content_id);


--
-- Name: content_reaction content_reaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_reaction
    ADD CONSTRAINT content_reaction_pkey PRIMARY KEY (content_id);


--
-- Name: content_report content_report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_report
    ADD CONSTRAINT content_report_pkey PRIMARY KEY (content_id);


--
-- Name: content_repost content_repost_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_repost
    ADD CONSTRAINT content_repost_pkey PRIMARY KEY (content_id);


--
-- Name: content_verification_claim content_verification_claim_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_verification_claim
    ADD CONSTRAINT content_verification_claim_pkey PRIMARY KEY (content_id);


--
-- Name: content_verification_target content_verification_target_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_verification_target
    ADD CONSTRAINT content_verification_target_pkey PRIMARY KEY (content_id, target_identity);


--
-- Name: content_verification_verify content_verification_verify_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_verification_verify
    ADD CONSTRAINT content_verification_verify_pkey PRIMARY KEY (content_id);


--
-- Name: default_follow_suggestion default_follow_suggestion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.default_follow_suggestion
    ADD CONSTRAINT default_follow_suggestion_pkey PRIMARY KEY (identity);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: follow follow_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follow
    ADD CONSTRAINT follow_pkey PRIMARY KEY (event_id);


--
-- Name: moderator moderator_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.moderator
    ADD CONSTRAINT moderator_pkey PRIMARY KEY (identity);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: pairing_session_claimer pairing_session_claimer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pairing_session_claimer
    ADD CONSTRAINT pairing_session_claimer_pkey PRIMARY KEY (digest_sha256, claimer_key_type, claimer_key);


--
-- Name: pairing_session pairing_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pairing_session
    ADD CONSTRAINT pairing_session_pkey PRIMARY KEY (issuer_identity);


--
-- Name: content_label pk-content_label; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_label
    ADD CONSTRAINT "pk-content_label" PRIMARY KEY (content_id, label_value);


--
-- Name: content_post_attributed_url pk-content_post_attributed_url; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_post_attributed_url
    ADD CONSTRAINT "pk-content_post_attributed_url" PRIMARY KEY (content_id, url);


--
-- Name: profile profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_pkey PRIMARY KEY (event_id);


--
-- Name: quote quote_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quote
    ADD CONSTRAINT quote_pkey PRIMARY KEY (event_id);


--
-- Name: reaction reaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reaction
    ADD CONSTRAINT reaction_pkey PRIMARY KEY (event_id);


--
-- Name: reaction_tally reaction_tally_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reaction_tally
    ADD CONSTRAINT reaction_tally_pkey PRIMARY KEY (event_id);


--
-- Name: reply reply_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reply
    ADD CONSTRAINT reply_pkey PRIMARY KEY (event_id);


--
-- Name: repost repost_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repost
    ADD CONSTRAINT repost_pkey PRIMARY KEY (event_id);


--
-- Name: seaql_migrations seaql_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seaql_migrations
    ADD CONSTRAINT seaql_migrations_pkey PRIMARY KEY (version);


--
-- Name: url_info_cache url_info_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.url_info_cache
    ADD CONSTRAINT url_info_cache_pkey PRIMARY KEY (url);


--
-- Name: verification_schema verification_schema_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_schema
    ADD CONSTRAINT verification_schema_pkey PRIMARY KEY (digest_type, digest_bytes);


--
-- Name: application_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX application_unique ON public.application USING btree (name, identifier, version, url);


--
-- Name: ban_created_at_identity_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ban_created_at_identity_idx ON public.ban USING btree (created_at, identity);


--
-- Name: block_blocker_blocked_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX block_blocker_blocked_idx ON public.block USING btree (blocker, blocked);


--
-- Name: content_delete_event_key_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_delete_event_key_idx ON public.content_delete USING btree (event_key_collection, event_key_identity, event_key_public_key_type, event_key_public_key, event_key_sequence);


--
-- Name: content_follow_identity_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_follow_identity_id_idx ON public.content_follow USING btree (identity_id);


--
-- Name: content_label_event_key_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_label_event_key_idx ON public.content_label USING btree (event_key_collection, event_key_identity, event_key_public_key_type, event_key_public_key, event_key_sequence);


--
-- Name: content_post_reply_parent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_post_reply_parent ON public.content_post USING btree (reply_parent_collection, reply_parent_identity, reply_parent_public_key_type, reply_parent_public_key, reply_parent_sequence);


--
-- Name: content_post_search_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_post_search_data ON public.content_post USING gin (search_data);


--
-- Name: content_profile_update_search_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_profile_update_search_data ON public.content_profile_update USING gin (search_data);


--
-- Name: content_reaction_event_key_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_reaction_event_key_idx ON public.content_reaction USING btree (event_key_collection, event_key_identity, event_key_public_key_type, event_key_public_key, event_key_sequence);


--
-- Name: content_verification_claim_fields_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_verification_claim_fields_gin ON public.content_verification_claim USING gin (fields jsonb_path_ops);


--
-- Name: content_verification_target_claim_event_key_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_verification_target_claim_event_key_idx ON public.content_verification_target USING btree (claim_event_key_collection, claim_event_key_identity, claim_event_key_public_key_type, claim_event_key_public_key, claim_event_key_sequence);


--
-- Name: content_verification_verify_claim_event_key_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_verification_verify_claim_event_key_idx ON public.content_verification_verify USING btree (claim_event_key_collection, claim_event_key_identity, claim_event_key_public_key_type, claim_event_key_public_key, claim_event_key_sequence);


--
-- Name: events_collection_created_at_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX events_collection_created_at_id_idx ON public.events USING btree (collection, created_at, id);


--
-- Name: events_content_digest_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX events_content_digest_idx ON public.events USING btree (content_digest_type, content_digest_bytes);


--
-- Name: events_identity_heads_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX events_identity_heads_idx ON public.events USING btree (identity, public_key_type, public_key, collection, sequence);


--
-- Name: follow_follower_followee_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX follow_follower_followee_idx ON public.follow USING btree (follower, followee);


--
-- Name: follow_identity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX follow_identity ON public.follow USING btree (follower) INCLUDE (followee);


--
-- Name: idx-content-digest; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "idx-content-digest" ON public.content USING btree (digest_type, digest_bytes);


--
-- Name: idx-content_attributed_to_reaction-url; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx-content_attributed_to_reaction-url" ON public.content_attributed_to_reaction USING btree (url);


--
-- Name: idx-content_blob-digest; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "idx-content_blob-digest" ON public.content_blob USING btree (digest_type, digest_bytes);


--
-- Name: idx-content_post_attributed_url-url; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx-content_post_attributed_url-url" ON public.content_post_attributed_url USING btree (url);


--
-- Name: idx-events-event_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "idx-events-event_key" ON public.events USING btree (collection, identity, public_key_type, public_key, sequence);


--
-- Name: idx_url_info_cache_updated_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_url_info_cache_updated_at ON public.url_info_cache USING btree (updated_at);


--
-- Name: notification_to_identity_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notification_to_identity_id_idx ON public.notification USING btree (to_identity, id);


--
-- Name: one_gravity_value; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX one_gravity_value ON public.gravity USING btree ((true));


--
-- Name: pairing_session_claimer_issuer_identity_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pairing_session_claimer_issuer_identity_idx ON public.pairing_session_claimer USING btree (issuer_identity);


--
-- Name: pairing_session_digest_sha256_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX pairing_session_digest_sha256_idx ON public.pairing_session USING btree (digest_sha256);


--
-- Name: profile_search_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX profile_search_data ON public.profile USING gin (search_data);


--
-- Name: quote_identity_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quote_identity_post ON public.quote USING btree (identity, post);


--
-- Name: quote_post_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quote_post_idx ON public.quote USING btree (post);


--
-- Name: reaction_identity_on_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reaction_identity_on_post ON public.reaction USING btree (identity, on_post);


--
-- Name: reaction_on_post_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reaction_on_post_idx ON public.reaction USING btree (on_post);


--
-- Name: reaction_tally_decayed_count; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reaction_tally_decayed_count ON public.reaction_tally USING btree (decayed_count DESC, event_id DESC) WHERE (decayed_count > (0)::numeric);


--
-- Name: reply_identity_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reply_identity_post ON public.reply USING btree (identity, post);


--
-- Name: reply_post_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reply_post_idx ON public.reply USING btree (post);


--
-- Name: repost_identity_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX repost_identity_post ON public.repost USING btree (identity, post);


--
-- Name: repost_post_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX repost_post_idx ON public.repost USING btree (post);


--
-- Name: content_attributed_to_reaction fk-content_attributed_to_reaction-content_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_attributed_to_reaction
    ADD CONSTRAINT "fk-content_attributed_to_reaction-content_id" FOREIGN KEY (content_id) REFERENCES public.content(id);


--
-- Name: content_label fk-content_label-content_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_label
    ADD CONSTRAINT "fk-content_label-content_id" FOREIGN KEY (content_id) REFERENCES public.content(id);


--
-- Name: content_post_attributed_url fk-content_post_attributed_url-content_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_post_attributed_url
    ADD CONSTRAINT "fk-content_post_attributed_url-content_id" FOREIGN KEY (content_id) REFERENCES public.content(id);


--
-- Name: content_report fk-content_report-content_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_report
    ADD CONSTRAINT "fk-content_report-content_id" FOREIGN KEY (content_id) REFERENCES public.content(id);


--
-- Name: content_repost fk-content_repost-content_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_repost
    ADD CONSTRAINT "fk-content_repost-content_id" FOREIGN KEY (content_id) REFERENCES public.content(id);


--
-- Name: events fk_events_application; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fk_events_application FOREIGN KEY (application_id) REFERENCES public.application(id);


--
-- PostgreSQL database dump complete
--

\unrestrict pDfhDFSWlMVwKJJCtVjCu9jpArxFvkN6yDVEZFQGYIycOWdbwu1Quua6JieaPNw

