// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { Color } from './sample/color.js';
export { Equipment } from './sample/equipment.js';
export { Monster } from './sample/monster.js';
export { Vec3 } from './sample/vec3.js';
export { Weapon } from './sample/weapon.js';
