version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dm_server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dm_server:
    build: .
    ports:
      - "8080:8080"  # HTTP API
      - "8081:8081"  # WebSocket
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/dm_server
      DM_SERVER_PORT: 8080
      DM_WEBSOCKET_PORT: 8081
      DM_CHALLENGE_KEY: secure-challenge-key-change-in-production
      RUST_LOG: info
    depends_on:
      - postgres
    volumes:
      - ./migrations:/app/migrations

volumes:
  postgres_data:
