"use strict";
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.QueryReferencesResponseEventItem = exports.QueryReferencesRequestCountReferences = exports.QueryReferencesRequestCountLWWElementReferences = exports.QueryReferencesRequestEvents = exports.QueryReferencesRequest = exports.RepeatedUInt64 = exports.StorageTypeEvent = exports.StorageTypeSystemState = exports.StorageTypeCRDTItem = exports.StorageTypeCRDTSetItem = exports.StorageTypeProcessState = exports.StorageTypeProcessSecret = exports.Vouch = exports.ClaimFieldEntry = exports.Claim = exports.Post = exports.Reference = exports.ResultTopStringReferences = exports.ResultEventsAndRelatedEventsAndCursor = exports.ExportBundle = exports.KeyPair = exports.PrivateKey = exports.RangesForSystem = exports.RangesForProcess = exports.Range = exports.PublicKeys = exports.AggregationBucket = exports.Events = exports.Delete = exports.Pointer = exports.Digest = exports.SystemProcesses = exports.Event = exports.ImageBundle = exports.ImageManifest = exports.Server = exports.LWWElement = exports.LWWElementSet = exports.LWWElementSet_Operation = exports.SignedEvent = exports.ModerationTag = exports.VectorClock = exports.Indices = exports.Index = exports.Process = exports.PublicKey = exports._capnpFileId = void 0;
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = require("capnp-ts");
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = "cafebabedeadbeef";
class PublicKey extends capnp_ts_1.Struct {
    getKeyType() { return capnp_ts_1.Struct.getUint64(0, this); }
    setKeyType(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    adoptKey(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownKey() { return capnp_ts_1.Struct.disown(this.getKey()); }
    getKey() { return capnp_ts_1.Struct.getData(0, this); }
    hasKey() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initKey(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setKey(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "PublicKey_" + super.toString(); }
}
exports.PublicKey = PublicKey;
PublicKey._capnp = { displayName: "PublicKey", id: "8f78230c9e58280c", size: new capnp_ts_1.ObjectSize(8, 1) };
class Process extends capnp_ts_1.Struct {
    adoptProcess(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownProcess() { return capnp_ts_1.Struct.disown(this.getProcess()); }
    getProcess() { return capnp_ts_1.Struct.getData(0, this); }
    hasProcess() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initProcess(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setProcess(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Process_" + super.toString(); }
}
exports.Process = Process;
Process._capnp = { displayName: "Process", id: "99b9c0019538054a", size: new capnp_ts_1.ObjectSize(0, 1) };
class Index extends capnp_ts_1.Struct {
    getIndexType() { return capnp_ts_1.Struct.getUint64(0, this); }
    setIndexType(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getLogicalClock() { return capnp_ts_1.Struct.getUint64(8, this); }
    setLogicalClock(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    toString() { return "Index_" + super.toString(); }
}
exports.Index = Index;
Index._capnp = { displayName: "Index", id: "a3ae4e3542c3fd02", size: new capnp_ts_1.ObjectSize(16, 0) };
class Indices extends capnp_ts_1.Struct {
    adoptIndices(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownIndices() { return capnp_ts_1.Struct.disown(this.getIndices()); }
    getIndices() { return capnp_ts_1.Struct.getList(0, Indices._Indices, this); }
    hasIndices() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initIndices(length) { return capnp_ts_1.Struct.initList(0, Indices._Indices, length, this); }
    setIndices(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Indices_" + super.toString(); }
}
exports.Indices = Indices;
Indices._capnp = { displayName: "Indices", id: "f9c9919f90851aac", size: new capnp_ts_1.ObjectSize(0, 1) };
class VectorClock extends capnp_ts_1.Struct {
    adoptLogicalClocks(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownLogicalClocks() { return capnp_ts_1.Struct.disown(this.getLogicalClocks()); }
    getLogicalClocks() { return capnp_ts_1.Struct.getList(0, capnp.Uint64List, this); }
    hasLogicalClocks() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initLogicalClocks(length) { return capnp_ts_1.Struct.initList(0, capnp.Uint64List, length, this); }
    setLogicalClocks(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "VectorClock_" + super.toString(); }
}
exports.VectorClock = VectorClock;
VectorClock._capnp = { displayName: "VectorClock", id: "c9422d29949ff104", size: new capnp_ts_1.ObjectSize(0, 1) };
class ModerationTag extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getLevel() { return capnp_ts_1.Struct.getUint32(0, this); }
    setLevel(value) { capnp_ts_1.Struct.setUint32(0, value, this); }
    toString() { return "ModerationTag_" + super.toString(); }
}
exports.ModerationTag = ModerationTag;
ModerationTag._capnp = { displayName: "ModerationTag", id: "8b0605a2e44cd67b", size: new capnp_ts_1.ObjectSize(8, 1) };
class SignedEvent extends capnp_ts_1.Struct {
    adoptSignature(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownSignature() { return capnp_ts_1.Struct.disown(this.getSignature()); }
    getSignature() { return capnp_ts_1.Struct.getData(0, this); }
    hasSignature() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSignature(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setSignature(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptEvent(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownEvent() { return capnp_ts_1.Struct.disown(this.getEvent()); }
    getEvent() { return capnp_ts_1.Struct.getData(1, this); }
    hasEvent() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initEvent(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setEvent(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptModerationTags(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownModerationTags() { return capnp_ts_1.Struct.disown(this.getModerationTags()); }
    getModerationTags() { return capnp_ts_1.Struct.getList(2, SignedEvent._ModerationTags, this); }
    hasModerationTags() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initModerationTags(length) { return capnp_ts_1.Struct.initList(2, SignedEvent._ModerationTags, length, this); }
    setModerationTags(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    toString() { return "SignedEvent_" + super.toString(); }
}
exports.SignedEvent = SignedEvent;
SignedEvent._capnp = { displayName: "SignedEvent", id: "e0aae5e9af657fc4", size: new capnp_ts_1.ObjectSize(0, 3) };
var LWWElementSet_Operation;
(function (LWWElementSet_Operation) {
    LWWElementSet_Operation[LWWElementSet_Operation["ADD"] = 0] = "ADD";
    LWWElementSet_Operation[LWWElementSet_Operation["REMOVE"] = 1] = "REMOVE";
})(LWWElementSet_Operation = exports.LWWElementSet_Operation || (exports.LWWElementSet_Operation = {}));
class LWWElementSet extends capnp_ts_1.Struct {
    getOperation() { return capnp_ts_1.Struct.getUint16(0, this); }
    setOperation(value) { capnp_ts_1.Struct.setUint16(0, value, this); }
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getData(0, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initValue(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getUnixMilliseconds() { return capnp_ts_1.Struct.getUint64(8, this); }
    setUnixMilliseconds(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    toString() { return "LWWElementSet_" + super.toString(); }
}
exports.LWWElementSet = LWWElementSet;
LWWElementSet.Operation = LWWElementSet_Operation;
LWWElementSet._capnp = { displayName: "LWWElementSet", id: "f9686d3fa4b8fee2", size: new capnp_ts_1.ObjectSize(16, 1) };
class LWWElement extends capnp_ts_1.Struct {
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getData(0, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initValue(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getUnixMilliseconds() { return capnp_ts_1.Struct.getUint64(0, this); }
    setUnixMilliseconds(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    toString() { return "LWWElement_" + super.toString(); }
}
exports.LWWElement = LWWElement;
LWWElement._capnp = { displayName: "LWWElement", id: "f863235793a5b398", size: new capnp_ts_1.ObjectSize(8, 1) };
class Server extends capnp_ts_1.Struct {
    getServer() { return capnp_ts_1.Struct.getText(0, this); }
    setServer(value) { capnp_ts_1.Struct.setText(0, value, this); }
    toString() { return "Server_" + super.toString(); }
}
exports.Server = Server;
Server._capnp = { displayName: "Server", id: "93486b77862eb8f0", size: new capnp_ts_1.ObjectSize(0, 1) };
class ImageManifest extends capnp_ts_1.Struct {
    getMime() { return capnp_ts_1.Struct.getText(0, this); }
    setMime(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getWidth() { return capnp_ts_1.Struct.getUint64(0, this); }
    setWidth(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getHeight() { return capnp_ts_1.Struct.getUint64(8, this); }
    setHeight(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getByteCount() { return capnp_ts_1.Struct.getUint64(16, this); }
    setByteCount(value) { capnp_ts_1.Struct.setUint64(16, value, this); }
    adoptProcess(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownProcess() { return capnp_ts_1.Struct.disown(this.getProcess()); }
    getProcess() { return capnp_ts_1.Struct.getStruct(1, Process, this); }
    hasProcess() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initProcess() { return capnp_ts_1.Struct.initStructAt(1, Process, this); }
    setProcess(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptSections(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownSections() { return capnp_ts_1.Struct.disown(this.getSections()); }
    getSections() { return capnp_ts_1.Struct.getList(2, ImageManifest._Sections, this); }
    hasSections() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initSections(length) { return capnp_ts_1.Struct.initList(2, ImageManifest._Sections, length, this); }
    setSections(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    toString() { return "ImageManifest_" + super.toString(); }
}
exports.ImageManifest = ImageManifest;
ImageManifest._capnp = { displayName: "ImageManifest", id: "ce5e542696397724", size: new capnp_ts_1.ObjectSize(24, 3) };
class ImageBundle extends capnp_ts_1.Struct {
    adoptImageManifests(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownImageManifests() { return capnp_ts_1.Struct.disown(this.getImageManifests()); }
    getImageManifests() { return capnp_ts_1.Struct.getList(0, ImageBundle._ImageManifests, this); }
    hasImageManifests() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initImageManifests(length) { return capnp_ts_1.Struct.initList(0, ImageBundle._ImageManifests, length, this); }
    setImageManifests(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "ImageBundle_" + super.toString(); }
}
exports.ImageBundle = ImageBundle;
ImageBundle._capnp = { displayName: "ImageBundle", id: "c6f36bd23847ff73", size: new capnp_ts_1.ObjectSize(0, 1) };
class Event extends capnp_ts_1.Struct {
    adoptSystem(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownSystem() { return capnp_ts_1.Struct.disown(this.getSystem()); }
    getSystem() { return capnp_ts_1.Struct.getStruct(0, PublicKey, this); }
    hasSystem() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSystem() { return capnp_ts_1.Struct.initStructAt(0, PublicKey, this); }
    setSystem(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptProcess(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownProcess() { return capnp_ts_1.Struct.disown(this.getProcess()); }
    getProcess() { return capnp_ts_1.Struct.getStruct(1, Process, this); }
    hasProcess() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initProcess() { return capnp_ts_1.Struct.initStructAt(1, Process, this); }
    setProcess(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getLogicalClock() { return capnp_ts_1.Struct.getUint64(0, this); }
    setLogicalClock(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getContentType() { return capnp_ts_1.Struct.getUint64(8, this); }
    setContentType(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    adoptContent(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownContent() { return capnp_ts_1.Struct.disown(this.getContent()); }
    getContent() { return capnp_ts_1.Struct.getData(2, this); }
    hasContent() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initContent(length) { return capnp_ts_1.Struct.initData(2, length, this); }
    setContent(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptVectorClock(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownVectorClock() { return capnp_ts_1.Struct.disown(this.getVectorClock()); }
    getVectorClock() { return capnp_ts_1.Struct.getStruct(3, VectorClock, this); }
    hasVectorClock() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initVectorClock() { return capnp_ts_1.Struct.initStructAt(3, VectorClock, this); }
    setVectorClock(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    adoptIndices(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownIndices() { return capnp_ts_1.Struct.disown(this.getIndices()); }
    getIndices() { return capnp_ts_1.Struct.getStruct(4, Indices, this); }
    hasIndices() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initIndices() { return capnp_ts_1.Struct.initStructAt(4, Indices, this); }
    setIndices(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    adoptLwwElementSet(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(5, this)); }
    disownLwwElementSet() { return capnp_ts_1.Struct.disown(this.getLwwElementSet()); }
    getLwwElementSet() { return capnp_ts_1.Struct.getStruct(5, LWWElementSet, this); }
    hasLwwElementSet() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(5, this)); }
    initLwwElementSet() { return capnp_ts_1.Struct.initStructAt(5, LWWElementSet, this); }
    setLwwElementSet(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(5, this)); }
    adoptLwwElement(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(6, this)); }
    disownLwwElement() { return capnp_ts_1.Struct.disown(this.getLwwElement()); }
    getLwwElement() { return capnp_ts_1.Struct.getStruct(6, LWWElement, this); }
    hasLwwElement() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(6, this)); }
    initLwwElement() { return capnp_ts_1.Struct.initStructAt(6, LWWElement, this); }
    setLwwElement(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(6, this)); }
    adoptReferences(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(7, this)); }
    disownReferences() { return capnp_ts_1.Struct.disown(this.getReferences()); }
    getReferences() { return capnp_ts_1.Struct.getList(7, Event._References, this); }
    hasReferences() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(7, this)); }
    initReferences(length) { return capnp_ts_1.Struct.initList(7, Event._References, length, this); }
    setReferences(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(7, this)); }
    getUnixMilliseconds() { return capnp_ts_1.Struct.getUint64(16, this); }
    setUnixMilliseconds(value) { capnp_ts_1.Struct.setUint64(16, value, this); }
    toString() { return "Event_" + super.toString(); }
}
exports.Event = Event;
Event._capnp = { displayName: "Event", id: "bafa8bdfc6d58a07", size: new capnp_ts_1.ObjectSize(24, 8) };
class SystemProcesses extends capnp_ts_1.Struct {
    adoptProcesses(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownProcesses() { return capnp_ts_1.Struct.disown(this.getProcesses()); }
    getProcesses() { return capnp_ts_1.Struct.getList(0, SystemProcesses._Processes, this); }
    hasProcesses() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initProcesses(length) { return capnp_ts_1.Struct.initList(0, SystemProcesses._Processes, length, this); }
    setProcesses(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "SystemProcesses_" + super.toString(); }
}
exports.SystemProcesses = SystemProcesses;
SystemProcesses._capnp = { displayName: "SystemProcesses", id: "ce77c5162778906f", size: new capnp_ts_1.ObjectSize(0, 1) };
class Digest extends capnp_ts_1.Struct {
    getDigestType() { return capnp_ts_1.Struct.getUint64(0, this); }
    setDigestType(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    adoptDigest(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownDigest() { return capnp_ts_1.Struct.disown(this.getDigest()); }
    getDigest() { return capnp_ts_1.Struct.getData(0, this); }
    hasDigest() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initDigest(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setDigest(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Digest_" + super.toString(); }
}
exports.Digest = Digest;
Digest._capnp = { displayName: "Digest", id: "8e76d496ea7896e5", size: new capnp_ts_1.ObjectSize(8, 1) };
class Pointer extends capnp_ts_1.Struct {
    adoptSystem(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownSystem() { return capnp_ts_1.Struct.disown(this.getSystem()); }
    getSystem() { return capnp_ts_1.Struct.getStruct(0, PublicKey, this); }
    hasSystem() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSystem() { return capnp_ts_1.Struct.initStructAt(0, PublicKey, this); }
    setSystem(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptProcess(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownProcess() { return capnp_ts_1.Struct.disown(this.getProcess()); }
    getProcess() { return capnp_ts_1.Struct.getStruct(1, Process, this); }
    hasProcess() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initProcess() { return capnp_ts_1.Struct.initStructAt(1, Process, this); }
    setProcess(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getLogicalClock() { return capnp_ts_1.Struct.getUint64(0, this); }
    setLogicalClock(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    adoptEventDigest(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownEventDigest() { return capnp_ts_1.Struct.disown(this.getEventDigest()); }
    getEventDigest() { return capnp_ts_1.Struct.getStruct(2, Digest, this); }
    hasEventDigest() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initEventDigest() { return capnp_ts_1.Struct.initStructAt(2, Digest, this); }
    setEventDigest(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    toString() { return "Pointer_" + super.toString(); }
}
exports.Pointer = Pointer;
Pointer._capnp = { displayName: "Pointer", id: "d55d9e609f849dfa", size: new capnp_ts_1.ObjectSize(8, 3) };
class Delete extends capnp_ts_1.Struct {
    adoptProcess(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownProcess() { return capnp_ts_1.Struct.disown(this.getProcess()); }
    getProcess() { return capnp_ts_1.Struct.getStruct(0, Process, this); }
    hasProcess() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initProcess() { return capnp_ts_1.Struct.initStructAt(0, Process, this); }
    setProcess(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getLogicalClock() { return capnp_ts_1.Struct.getUint64(0, this); }
    setLogicalClock(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    adoptIndices(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownIndices() { return capnp_ts_1.Struct.disown(this.getIndices()); }
    getIndices() { return capnp_ts_1.Struct.getStruct(1, Indices, this); }
    hasIndices() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initIndices() { return capnp_ts_1.Struct.initStructAt(1, Indices, this); }
    setIndices(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getUnixMilliseconds() { return capnp_ts_1.Struct.getUint64(8, this); }
    setUnixMilliseconds(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getContentType() { return capnp_ts_1.Struct.getUint64(16, this); }
    setContentType(value) { capnp_ts_1.Struct.setUint64(16, value, this); }
    toString() { return "Delete_" + super.toString(); }
}
exports.Delete = Delete;
Delete._capnp = { displayName: "Delete", id: "a419d8467a97a941", size: new capnp_ts_1.ObjectSize(24, 2) };
class Events extends capnp_ts_1.Struct {
    adoptEvents(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownEvents() { return capnp_ts_1.Struct.disown(this.getEvents()); }
    getEvents() { return capnp_ts_1.Struct.getList(0, Events._Events, this); }
    hasEvents() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initEvents(length) { return capnp_ts_1.Struct.initList(0, Events._Events, length, this); }
    setEvents(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Events_" + super.toString(); }
}
exports.Events = Events;
Events._capnp = { displayName: "Events", id: "af849d426324b76d", size: new capnp_ts_1.ObjectSize(0, 1) };
class AggregationBucket extends capnp_ts_1.Struct {
    adoptKey(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownKey() { return capnp_ts_1.Struct.disown(this.getKey()); }
    getKey() { return capnp_ts_1.Struct.getData(0, this); }
    hasKey() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initKey(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setKey(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getValue() { return capnp_ts_1.Struct.getInt64(0, this); }
    setValue(value) { capnp_ts_1.Struct.setInt64(0, value, this); }
    toString() { return "AggregationBucket_" + super.toString(); }
}
exports.AggregationBucket = AggregationBucket;
AggregationBucket._capnp = { displayName: "AggregationBucket", id: "ee458f6de824422d", size: new capnp_ts_1.ObjectSize(8, 1) };
class PublicKeys extends capnp_ts_1.Struct {
    adoptSystems(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownSystems() { return capnp_ts_1.Struct.disown(this.getSystems()); }
    getSystems() { return capnp_ts_1.Struct.getList(0, PublicKeys._Systems, this); }
    hasSystems() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSystems(length) { return capnp_ts_1.Struct.initList(0, PublicKeys._Systems, length, this); }
    setSystems(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "PublicKeys_" + super.toString(); }
}
exports.PublicKeys = PublicKeys;
PublicKeys._capnp = { displayName: "PublicKeys", id: "e792b2ec2bcd557e", size: new capnp_ts_1.ObjectSize(0, 1) };
class Range extends capnp_ts_1.Struct {
    getLow() { return capnp_ts_1.Struct.getUint64(0, this); }
    setLow(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getHigh() { return capnp_ts_1.Struct.getUint64(8, this); }
    setHigh(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    toString() { return "Range_" + super.toString(); }
}
exports.Range = Range;
Range._capnp = { displayName: "Range", id: "9a4306bd0dcb2f66", size: new capnp_ts_1.ObjectSize(16, 0) };
class RangesForProcess extends capnp_ts_1.Struct {
    adoptProcess(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownProcess() { return capnp_ts_1.Struct.disown(this.getProcess()); }
    getProcess() { return capnp_ts_1.Struct.getStruct(0, Process, this); }
    hasProcess() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initProcess() { return capnp_ts_1.Struct.initStructAt(0, Process, this); }
    setProcess(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptRanges(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownRanges() { return capnp_ts_1.Struct.disown(this.getRanges()); }
    getRanges() { return capnp_ts_1.Struct.getList(1, RangesForProcess._Ranges, this); }
    hasRanges() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initRanges(length) { return capnp_ts_1.Struct.initList(1, RangesForProcess._Ranges, length, this); }
    setRanges(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "RangesForProcess_" + super.toString(); }
}
exports.RangesForProcess = RangesForProcess;
RangesForProcess._capnp = { displayName: "RangesForProcess", id: "b57055d2e476a6f5", size: new capnp_ts_1.ObjectSize(0, 2) };
class RangesForSystem extends capnp_ts_1.Struct {
    adoptRangesForProcesses(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownRangesForProcesses() { return capnp_ts_1.Struct.disown(this.getRangesForProcesses()); }
    getRangesForProcesses() { return capnp_ts_1.Struct.getList(0, RangesForSystem._RangesForProcesses, this); }
    hasRangesForProcesses() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initRangesForProcesses(length) { return capnp_ts_1.Struct.initList(0, RangesForSystem._RangesForProcesses, length, this); }
    setRangesForProcesses(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "RangesForSystem_" + super.toString(); }
}
exports.RangesForSystem = RangesForSystem;
RangesForSystem._capnp = { displayName: "RangesForSystem", id: "d676fa689991beef", size: new capnp_ts_1.ObjectSize(0, 1) };
class PrivateKey extends capnp_ts_1.Struct {
    getKeyType() { return capnp_ts_1.Struct.getUint64(0, this); }
    setKeyType(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    adoptKey(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownKey() { return capnp_ts_1.Struct.disown(this.getKey()); }
    getKey() { return capnp_ts_1.Struct.getData(0, this); }
    hasKey() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initKey(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setKey(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "PrivateKey_" + super.toString(); }
}
exports.PrivateKey = PrivateKey;
PrivateKey._capnp = { displayName: "PrivateKey", id: "8ffe1e358cb8a350", size: new capnp_ts_1.ObjectSize(8, 1) };
class KeyPair extends capnp_ts_1.Struct {
    getKeyType() { return capnp_ts_1.Struct.getUint64(0, this); }
    setKeyType(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    adoptPrivateKey(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownPrivateKey() { return capnp_ts_1.Struct.disown(this.getPrivateKey()); }
    getPrivateKey() { return capnp_ts_1.Struct.getData(0, this); }
    hasPrivateKey() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initPrivateKey(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setPrivateKey(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptPublicKey(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownPublicKey() { return capnp_ts_1.Struct.disown(this.getPublicKey()); }
    getPublicKey() { return capnp_ts_1.Struct.getData(1, this); }
    hasPublicKey() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initPublicKey(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setPublicKey(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "KeyPair_" + super.toString(); }
}
exports.KeyPair = KeyPair;
KeyPair._capnp = { displayName: "KeyPair", id: "b6f40b1d74d006b7", size: new capnp_ts_1.ObjectSize(8, 2) };
class ExportBundle extends capnp_ts_1.Struct {
    adoptKeyPair(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownKeyPair() { return capnp_ts_1.Struct.disown(this.getKeyPair()); }
    getKeyPair() { return capnp_ts_1.Struct.getStruct(0, KeyPair, this); }
    hasKeyPair() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initKeyPair() { return capnp_ts_1.Struct.initStructAt(0, KeyPair, this); }
    setKeyPair(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptEvents(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownEvents() { return capnp_ts_1.Struct.disown(this.getEvents()); }
    getEvents() { return capnp_ts_1.Struct.getStruct(1, Events, this); }
    hasEvents() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initEvents() { return capnp_ts_1.Struct.initStructAt(1, Events, this); }
    setEvents(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "ExportBundle_" + super.toString(); }
}
exports.ExportBundle = ExportBundle;
ExportBundle._capnp = { displayName: "ExportBundle", id: "c5743d1877018b24", size: new capnp_ts_1.ObjectSize(0, 2) };
class ResultEventsAndRelatedEventsAndCursor extends capnp_ts_1.Struct {
    adoptResultEvents(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownResultEvents() { return capnp_ts_1.Struct.disown(this.getResultEvents()); }
    getResultEvents() { return capnp_ts_1.Struct.getStruct(0, Events, this); }
    hasResultEvents() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initResultEvents() { return capnp_ts_1.Struct.initStructAt(0, Events, this); }
    setResultEvents(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptRelatedEvents(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownRelatedEvents() { return capnp_ts_1.Struct.disown(this.getRelatedEvents()); }
    getRelatedEvents() { return capnp_ts_1.Struct.getStruct(1, Events, this); }
    hasRelatedEvents() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initRelatedEvents() { return capnp_ts_1.Struct.initStructAt(1, Events, this); }
    setRelatedEvents(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptCursor(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownCursor() { return capnp_ts_1.Struct.disown(this.getCursor()); }
    getCursor() { return capnp_ts_1.Struct.getData(2, this); }
    hasCursor() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initCursor(length) { return capnp_ts_1.Struct.initData(2, length, this); }
    setCursor(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    toString() { return "ResultEventsAndRelatedEventsAndCursor_" + super.toString(); }
}
exports.ResultEventsAndRelatedEventsAndCursor = ResultEventsAndRelatedEventsAndCursor;
ResultEventsAndRelatedEventsAndCursor._capnp = { displayName: "ResultEventsAndRelatedEventsAndCursor", id: "b383a4700d7a2bd2", size: new capnp_ts_1.ObjectSize(0, 3) };
class ResultTopStringReferences extends capnp_ts_1.Struct {
    adoptBuckets(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownBuckets() { return capnp_ts_1.Struct.disown(this.getBuckets()); }
    getBuckets() { return capnp_ts_1.Struct.getList(0, ResultTopStringReferences._Buckets, this); }
    hasBuckets() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initBuckets(length) { return capnp_ts_1.Struct.initList(0, ResultTopStringReferences._Buckets, length, this); }
    setBuckets(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "ResultTopStringReferences_" + super.toString(); }
}
exports.ResultTopStringReferences = ResultTopStringReferences;
ResultTopStringReferences._capnp = { displayName: "ResultTopStringReferences", id: "80c949f3140ddfb4", size: new capnp_ts_1.ObjectSize(0, 1) };
class Reference extends capnp_ts_1.Struct {
    getReferenceType() { return capnp_ts_1.Struct.getUint64(0, this); }
    setReferenceType(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    adoptReference(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownReference() { return capnp_ts_1.Struct.disown(this.getReference()); }
    getReference() { return capnp_ts_1.Struct.getData(0, this); }
    hasReference() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initReference(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setReference(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Reference_" + super.toString(); }
}
exports.Reference = Reference;
Reference._capnp = { displayName: "Reference", id: "b97fc3ba7cf7f4c3", size: new capnp_ts_1.ObjectSize(8, 1) };
class Post extends capnp_ts_1.Struct {
    getContent() { return capnp_ts_1.Struct.getText(0, this); }
    setContent(value) { capnp_ts_1.Struct.setText(0, value, this); }
    adoptImage(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownImage() { return capnp_ts_1.Struct.disown(this.getImage()); }
    getImage() { return capnp_ts_1.Struct.getStruct(1, ImageManifest, this); }
    hasImage() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initImage() { return capnp_ts_1.Struct.initStructAt(1, ImageManifest, this); }
    setImage(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "Post_" + super.toString(); }
}
exports.Post = Post;
Post._capnp = { displayName: "Post", id: "91c54962a27f3dc8", size: new capnp_ts_1.ObjectSize(0, 2) };
class Claim extends capnp_ts_1.Struct {
    getClaimType() { return capnp_ts_1.Struct.getUint64(0, this); }
    setClaimType(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    adoptClaimFields(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownClaimFields() { return capnp_ts_1.Struct.disown(this.getClaimFields()); }
    getClaimFields() { return capnp_ts_1.Struct.getList(0, Claim._ClaimFields, this); }
    hasClaimFields() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initClaimFields(length) { return capnp_ts_1.Struct.initList(0, Claim._ClaimFields, length, this); }
    setClaimFields(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Claim_" + super.toString(); }
}
exports.Claim = Claim;
Claim._capnp = { displayName: "Claim", id: "d6921a78f5be463e", size: new capnp_ts_1.ObjectSize(8, 1) };
class ClaimFieldEntry extends capnp_ts_1.Struct {
    getKey() { return capnp_ts_1.Struct.getUint64(0, this); }
    setKey(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getValue() { return capnp_ts_1.Struct.getText(0, this); }
    setValue(value) { capnp_ts_1.Struct.setText(0, value, this); }
    toString() { return "ClaimFieldEntry_" + super.toString(); }
}
exports.ClaimFieldEntry = ClaimFieldEntry;
ClaimFieldEntry._capnp = { displayName: "ClaimFieldEntry", id: "d91165782b0f00da", size: new capnp_ts_1.ObjectSize(8, 1) };
class Vouch extends capnp_ts_1.Struct {
    toString() { return "Vouch_" + super.toString(); }
}
exports.Vouch = Vouch;
Vouch._capnp = { displayName: "Vouch", id: "ce819479b726b86f", size: new capnp_ts_1.ObjectSize(0, 0) };
class StorageTypeProcessSecret extends capnp_ts_1.Struct {
    adoptSystem(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownSystem() { return capnp_ts_1.Struct.disown(this.getSystem()); }
    getSystem() { return capnp_ts_1.Struct.getStruct(0, PrivateKey, this); }
    hasSystem() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSystem() { return capnp_ts_1.Struct.initStructAt(0, PrivateKey, this); }
    setSystem(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptProcess(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownProcess() { return capnp_ts_1.Struct.disown(this.getProcess()); }
    getProcess() { return capnp_ts_1.Struct.getStruct(1, Process, this); }
    hasProcess() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initProcess() { return capnp_ts_1.Struct.initStructAt(1, Process, this); }
    setProcess(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "StorageTypeProcessSecret_" + super.toString(); }
}
exports.StorageTypeProcessSecret = StorageTypeProcessSecret;
StorageTypeProcessSecret._capnp = { displayName: "StorageTypeProcessSecret", id: "a84efba2acb99c05", size: new capnp_ts_1.ObjectSize(0, 2) };
class StorageTypeProcessState extends capnp_ts_1.Struct {
    getLogicalClock() { return capnp_ts_1.Struct.getUint64(0, this); }
    setLogicalClock(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    adoptRanges(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownRanges() { return capnp_ts_1.Struct.disown(this.getRanges()); }
    getRanges() { return capnp_ts_1.Struct.getList(0, StorageTypeProcessState._Ranges, this); }
    hasRanges() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initRanges(length) { return capnp_ts_1.Struct.initList(0, StorageTypeProcessState._Ranges, length, this); }
    setRanges(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptIndices(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownIndices() { return capnp_ts_1.Struct.disown(this.getIndices()); }
    getIndices() { return capnp_ts_1.Struct.getStruct(1, Indices, this); }
    hasIndices() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initIndices() { return capnp_ts_1.Struct.initStructAt(1, Indices, this); }
    setIndices(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "StorageTypeProcessState_" + super.toString(); }
}
exports.StorageTypeProcessState = StorageTypeProcessState;
StorageTypeProcessState._capnp = { displayName: "StorageTypeProcessState", id: "8036b18b80765e14", size: new capnp_ts_1.ObjectSize(8, 2) };
class StorageTypeCRDTSetItem extends capnp_ts_1.Struct {
    getContentType() { return capnp_ts_1.Struct.getUint64(0, this); }
    setContentType(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getData(0, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initValue(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getUnixMilliseconds() { return capnp_ts_1.Struct.getUint64(8, this); }
    setUnixMilliseconds(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getOperation() { return capnp_ts_1.Struct.getUint16(16, this); }
    setOperation(value) { capnp_ts_1.Struct.setUint16(16, value, this); }
    toString() { return "StorageTypeCRDTSetItem_" + super.toString(); }
}
exports.StorageTypeCRDTSetItem = StorageTypeCRDTSetItem;
StorageTypeCRDTSetItem._capnp = { displayName: "StorageTypeCRDTSetItem", id: "dea322f8849d7629", size: new capnp_ts_1.ObjectSize(24, 1) };
class StorageTypeCRDTItem extends capnp_ts_1.Struct {
    getContentType() { return capnp_ts_1.Struct.getUint64(0, this); }
    setContentType(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getData(0, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initValue(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getUnixMilliseconds() { return capnp_ts_1.Struct.getUint64(8, this); }
    setUnixMilliseconds(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    toString() { return "StorageTypeCRDTItem_" + super.toString(); }
}
exports.StorageTypeCRDTItem = StorageTypeCRDTItem;
StorageTypeCRDTItem._capnp = { displayName: "StorageTypeCRDTItem", id: "bb6f50a2c43edd11", size: new capnp_ts_1.ObjectSize(16, 1) };
class StorageTypeSystemState extends capnp_ts_1.Struct {
    adoptProcesses(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownProcesses() { return capnp_ts_1.Struct.disown(this.getProcesses()); }
    getProcesses() { return capnp_ts_1.Struct.getList(0, StorageTypeSystemState._Processes, this); }
    hasProcesses() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initProcesses(length) { return capnp_ts_1.Struct.initList(0, StorageTypeSystemState._Processes, length, this); }
    setProcesses(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptCrdtItems(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownCrdtItems() { return capnp_ts_1.Struct.disown(this.getCrdtItems()); }
    getCrdtItems() { return capnp_ts_1.Struct.getList(1, StorageTypeSystemState._CrdtItems, this); }
    hasCrdtItems() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initCrdtItems(length) { return capnp_ts_1.Struct.initList(1, StorageTypeSystemState._CrdtItems, length, this); }
    setCrdtItems(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "StorageTypeSystemState_" + super.toString(); }
}
exports.StorageTypeSystemState = StorageTypeSystemState;
StorageTypeSystemState._capnp = { displayName: "StorageTypeSystemState", id: "9d46599873ea4d72", size: new capnp_ts_1.ObjectSize(0, 2) };
class StorageTypeEvent extends capnp_ts_1.Struct {
    adoptEvent(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownEvent() { return capnp_ts_1.Struct.disown(this.getEvent()); }
    getEvent() { return capnp_ts_1.Struct.getStruct(0, SignedEvent, this); }
    hasEvent() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initEvent() { return capnp_ts_1.Struct.initStructAt(0, SignedEvent, this); }
    setEvent(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptMutationPointer(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownMutationPointer() { return capnp_ts_1.Struct.disown(this.getMutationPointer()); }
    getMutationPointer() { return capnp_ts_1.Struct.getStruct(1, Pointer, this); }
    hasMutationPointer() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initMutationPointer() { return capnp_ts_1.Struct.initStructAt(1, Pointer, this); }
    setMutationPointer(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "StorageTypeEvent_" + super.toString(); }
}
exports.StorageTypeEvent = StorageTypeEvent;
StorageTypeEvent._capnp = { displayName: "StorageTypeEvent", id: "934201f10ac1d7bd", size: new capnp_ts_1.ObjectSize(0, 2) };
class RepeatedUInt64 extends capnp_ts_1.Struct {
    adoptNumbers(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownNumbers() { return capnp_ts_1.Struct.disown(this.getNumbers()); }
    getNumbers() { return capnp_ts_1.Struct.getList(0, capnp.Uint64List, this); }
    hasNumbers() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initNumbers(length) { return capnp_ts_1.Struct.initList(0, capnp.Uint64List, length, this); }
    setNumbers(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "RepeatedUInt64_" + super.toString(); }
}
exports.RepeatedUInt64 = RepeatedUInt64;
RepeatedUInt64._capnp = { displayName: "RepeatedUInt64", id: "dd1b63b30bf726f1", size: new capnp_ts_1.ObjectSize(0, 1) };
class QueryReferencesRequest extends capnp_ts_1.Struct {
    adoptReference(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownReference() { return capnp_ts_1.Struct.disown(this.getReference()); }
    getReference() { return capnp_ts_1.Struct.getStruct(0, Reference, this); }
    hasReference() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initReference() { return capnp_ts_1.Struct.initStructAt(0, Reference, this); }
    setReference(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptCursor(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownCursor() { return capnp_ts_1.Struct.disown(this.getCursor()); }
    getCursor() { return capnp_ts_1.Struct.getData(1, this); }
    hasCursor() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initCursor(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setCursor(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptRequestEvents(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownRequestEvents() { return capnp_ts_1.Struct.disown(this.getRequestEvents()); }
    getRequestEvents() { return capnp_ts_1.Struct.getStruct(2, QueryReferencesRequestEvents, this); }
    hasRequestEvents() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initRequestEvents() { return capnp_ts_1.Struct.initStructAt(2, QueryReferencesRequestEvents, this); }
    setRequestEvents(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptCountLwwElementReferences(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownCountLwwElementReferences() { return capnp_ts_1.Struct.disown(this.getCountLwwElementReferences()); }
    getCountLwwElementReferences() { return capnp_ts_1.Struct.getList(3, QueryReferencesRequest._CountLwwElementReferences, this); }
    hasCountLwwElementReferences() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initCountLwwElementReferences(length) { return capnp_ts_1.Struct.initList(3, QueryReferencesRequest._CountLwwElementReferences, length, this); }
    setCountLwwElementReferences(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    adoptCountReferences(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownCountReferences() { return capnp_ts_1.Struct.disown(this.getCountReferences()); }
    getCountReferences() { return capnp_ts_1.Struct.getList(4, QueryReferencesRequest._CountReferences, this); }
    hasCountReferences() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initCountReferences(length) { return capnp_ts_1.Struct.initList(4, QueryReferencesRequest._CountReferences, length, this); }
    setCountReferences(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    adoptExtraByteReferences(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(5, this)); }
    disownExtraByteReferences() { return capnp_ts_1.Struct.disown(this.getExtraByteReferences()); }
    getExtraByteReferences() { return capnp_ts_1.Struct.getList(5, capnp.DataList, this); }
    hasExtraByteReferences() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(5, this)); }
    initExtraByteReferences(length) { return capnp_ts_1.Struct.initList(5, capnp.DataList, length, this); }
    setExtraByteReferences(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(5, this)); }
    toString() { return "QueryReferencesRequest_" + super.toString(); }
}
exports.QueryReferencesRequest = QueryReferencesRequest;
QueryReferencesRequest._capnp = { displayName: "QueryReferencesRequest", id: "ec708ef95da53efd", size: new capnp_ts_1.ObjectSize(0, 6) };
class QueryReferencesRequestEvents extends capnp_ts_1.Struct {
    getFromType() { return capnp_ts_1.Struct.getUint64(0, this); }
    setFromType(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    adoptCountLwwElementReferences(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownCountLwwElementReferences() { return capnp_ts_1.Struct.disown(this.getCountLwwElementReferences()); }
    getCountLwwElementReferences() { return capnp_ts_1.Struct.getList(0, QueryReferencesRequestEvents._CountLwwElementReferences, this); }
    hasCountLwwElementReferences() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initCountLwwElementReferences(length) { return capnp_ts_1.Struct.initList(0, QueryReferencesRequestEvents._CountLwwElementReferences, length, this); }
    setCountLwwElementReferences(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptCountReferences(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownCountReferences() { return capnp_ts_1.Struct.disown(this.getCountReferences()); }
    getCountReferences() { return capnp_ts_1.Struct.getList(1, QueryReferencesRequestEvents._CountReferences, this); }
    hasCountReferences() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initCountReferences(length) { return capnp_ts_1.Struct.initList(1, QueryReferencesRequestEvents._CountReferences, length, this); }
    setCountReferences(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "QueryReferencesRequestEvents_" + super.toString(); }
}
exports.QueryReferencesRequestEvents = QueryReferencesRequestEvents;
QueryReferencesRequestEvents._capnp = { displayName: "QueryReferencesRequestEvents", id: "b1f94f9af260425d", size: new capnp_ts_1.ObjectSize(8, 2) };
class QueryReferencesRequestCountLWWElementReferences extends capnp_ts_1.Struct {
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getData(0, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initValue(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getFromType() { return capnp_ts_1.Struct.getUint64(0, this); }
    setFromType(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    toString() { return "QueryReferencesRequestCountLWWElementReferences_" + super.toString(); }
}
exports.QueryReferencesRequestCountLWWElementReferences = QueryReferencesRequestCountLWWElementReferences;
QueryReferencesRequestCountLWWElementReferences._capnp = { displayName: "QueryReferencesRequestCountLWWElementReferences", id: "992c2f6dec96beb2", size: new capnp_ts_1.ObjectSize(8, 1) };
class QueryReferencesRequestCountReferences extends capnp_ts_1.Struct {
    getFromType() { return capnp_ts_1.Struct.getUint64(0, this); }
    setFromType(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    toString() { return "QueryReferencesRequestCountReferences_" + super.toString(); }
}
exports.QueryReferencesRequestCountReferences = QueryReferencesRequestCountReferences;
QueryReferencesRequestCountReferences._capnp = { displayName: "QueryReferencesRequestCountReferences", id: "e8e59bd49a36ea88", size: new capnp_ts_1.ObjectSize(8, 0) };
class QueryReferencesResponseEventItem extends capnp_ts_1.Struct {
    adoptEvent(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownEvent() { return capnp_ts_1.Struct.disown(this.getEvent()); }
    getEvent() { return capnp_ts_1.Struct.getStruct(0, SignedEvent, this); }
    hasEvent() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initEvent() { return capnp_ts_1.Struct.initStructAt(0, SignedEvent, this); }
    setEvent(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "QueryReferencesResponseEventItem_" + super.toString(); }
}
exports.QueryReferencesResponseEventItem = QueryReferencesResponseEventItem;
QueryReferencesResponseEventItem._capnp = { displayName: "QueryReferencesResponseEventItem", id: "f44b5002a4bb217d", size: new capnp_ts_1.ObjectSize(0, 1) };
Indices._Indices = capnp.CompositeList(Index);
SignedEvent._ModerationTags = capnp.CompositeList(ModerationTag);
ImageManifest._Sections = capnp.CompositeList(Range);
ImageBundle._ImageManifests = capnp.CompositeList(ImageManifest);
Event._References = capnp.CompositeList(Reference);
SystemProcesses._Processes = capnp.CompositeList(Process);
Events._Events = capnp.CompositeList(SignedEvent);
PublicKeys._Systems = capnp.CompositeList(PublicKey);
RangesForProcess._Ranges = capnp.CompositeList(Range);
RangesForSystem._RangesForProcesses = capnp.CompositeList(RangesForProcess);
ResultTopStringReferences._Buckets = capnp.CompositeList(AggregationBucket);
Claim._ClaimFields = capnp.CompositeList(ClaimFieldEntry);
StorageTypeProcessState._Ranges = capnp.CompositeList(Range);
StorageTypeSystemState._Processes = capnp.CompositeList(Process);
StorageTypeSystemState._CrdtItems = capnp.CompositeList(StorageTypeCRDTItem);
QueryReferencesRequest._CountLwwElementReferences = capnp.CompositeList(QueryReferencesRequestCountLWWElementReferences);
QueryReferencesRequest._CountReferences = capnp.CompositeList(QueryReferencesRequestCountReferences);
QueryReferencesRequestEvents._CountLwwElementReferences = capnp.CompositeList(QueryReferencesRequestCountLWWElementReferences);
QueryReferencesRequestEvents._CountReferences = capnp.CompositeList(QueryReferencesRequestCountReferences);
