replicaCount: 1

image:
  repository: gitlab.futo.org:5050/polycentric/polycentric
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
# If your image is in a private registry, specify imagePullSecrets:
# imagePullSecrets:
#   - name: myregistrykey

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  name: ""

podAnnotations: {}
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: api.sfo2.cluster.futoinfra.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - api.sfo2.cluster.futoinfra.com
      secretName: polycentric-tls

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: RUST_LOG
    value: "server=info"
  - name: ADMIN_TOKEN
    value: "123"
